### ISSUE TITLE
Modelo 3 de la tarea

### ISSUE THREAD

**Issue by nmorales1** [IIC2115/Syllabus-2018-1#10]
En el Modelo 3 de la Tarea no se especifica ninguna conexión entre Macul y las demás estaciones. ¿Esto hay que considerarlo como una restricción cuando se ejecuten los códigos o si el que lo está usando carga el modelo 3 no pedirá ni ir ni partir de Macul?

**Comment by Hernan4444** [comment]
@nmorales1 puedes suponer que no iremos ni partiremos de esa estación para el modelo 3.

Saludos!! ✌️
