### ISSUE TITLE
tarea1- compra/pago de costo_entrada para las atracciones

### ISSUE THREAD

**Issue by fjorrego** [IIC2115/Syllabus-2018-1#100]
En el enunciado sale que cuando una persona está sin ninguna atraccion, se le asigna la atracción más cara que pueda pagar y se va a la fila de esta. Sin embargo, por los cambios (duplicacion) de precios de las entradas, hay veces en que cuando el visitante le toca entrar al juego, ya no tiene dinero suficiente para pagarlo. En estos casos que se hace? Esta bien hacer que cuando uno asigna un visitante a alguna fila, este tenga que comprar un ticket de entrada y de esta forma si el precio del ticket sube cuando le toque subirse, él pagará la cantidad que costaba cuando llegó a la fila (ya que ya había comprado el ticket).

**Comment by Hernan4444** [comment]
@fjorrego ante esa situación, la persona se sale de la cola al momento que suben los precios o al momento que le toca entrar y ya no dispone de la plata. Pero que no compre el ticket.

Saludos ✌️

**Comment by vickyenberg** [comment]
En caso de que la persona se salga de la cola cuando suban los precios, la ganancia del dueño no será la misma que si la persona se va al momento de estar al principio de la cola... o no?

**Comment by fjmunoz3** [comment]
Otra duda a propósito (no sé si es obvio), pero siempre el cliente elegirá la atracción más cara que pueda costear?

**Comment by Hernan4444** [comment]
@vickyenberg si, van a cambiar las ganancias ante esa decision, pero lo tendremos en cuanta al momento de corregir.
@fjmunoz3 si, siempre elegirá eso. Así evitamos las instancias de decisión que pueden afectar el resultado como lo que justo le comenté a @vickyenberg 

Saludos ✌️
