### ISSUE TITLE
Tarea 1 - Funcionamiento atracciones

### ISSUE THREAD

**Issue by vickyenberg** [IIC2115/Syllabus-2018-1#101]
Hola,
¿Las atracciones comienzan a funcionar cada cierto tiempo o una vez que tienen llena su capacidad comienzan a funcionar?

**Comment by Hernan4444** [comment]
@vickyenberg las atracciones funcionan cada vez que pueden dar una vuelta, no importa si hay gente o no en la cola, o si hay gente subida o no.

Saludos ✌️

**Comment by SebaVasquez** [comment]
Pero desde el inicio de la simulación todas las atracciones del dueño deben estar funcionando?. No tiene mucho sentido que una persona que llegue no pueda subirse porque una atracción esta funcionando vacía.

Gracias,

**Comment by BrunoLertora** [comment]
Me imagino que si es que hay gente en la cola, se sube a la mayor cantidad de gente posible y después se pone a funcionar (lo que puede pasar en el mismo instante de tiempo). Lo que creo que dice @Hernan4444 (corrígeme si me equivoco), es que si no hay nadie en la cola, el juego se pone a funcionar igual.

**Comment by Hernan4444** [comment]
@mister-robot esta issue fue respondida hace 6 días, no se puede realizar ese supuesto.

Edit: Para que no pase de nuevo esto, te recomiendo hacerle watch al repositorio.

Saludos ✌️
