### ISSUE TITLE
[Tarea 1]

### ISSUE THREAD

**Issue by aeavalos** [IIC2115/Syllabus-2018-1#102]
Tengo dos dudas:

1.- Las personas evacuadas al fallar una atracción son tanto las personas en vuelta como las personas que están en la fila o solo los que están en vuelta??

2.- La simulación debe durar más de un día? O puedo hacer que la simulación dure un día y luego repetirla para decir que son días diferentes??

Desde ya muchas gracias

**Comment by Hernan4444** [comment]
@aeavalos hola ✋ 
1. Solo las que están en vuelta
2. Tiene que durar más de un día, como les dimos una base con pocas personas, es muy probable que dure un día y ya no existan personas, pero nosotros podemos probar con una base de 10000 personas y con tiempos de llegadas distintos, así que necesitamos que pueda durar más de un día.

Saludos ✌️

**Comment by aeavalos** [comment]
Y cuando una atracción falla, las personas vuelven a la fila y esperan la hora hasta que el juego se pone en marcha de nuevo o salen a buscar otro juego, la misma pregunta para las personas que están en la fila de la atracción. Además, debo indemnizar a estos también o solo a los que se subieron cuando falló?

**Comment by fjmunoz3** [comment]
A propósito de la duración de la simulación... los tiempos de llegada dan como para simular 5 horas y con eso no podemos armar la tabla que se nos pide en la página 5. Tenemos que escribir un código que sea capaz de generar la tabla cuando hayan personas suficientes para 60 días? En otras palabras, nuestro último día de la tabla tiene que ser el último día en que llegó un cliente (independiente de cuántos sean?).
