### ISSUE TITLE
[Tarea 1] Compra de nuevas atracciones

### ISSUE THREAD

**Issue by fjmunoz3** [IIC2115/Syllabus-2018-1#103]
Hola, en el enunciado dice:
"Cada vez que el dueño obtenga 500.000 HC, invertira
la mitad de su capital en una nueva atraccion, que sera la que tenga el mayor costo de entrada"
Para invertir, elije la atracción de entrada más cara de entre las que ya tiene? o de entre las que no tiene? o de entre todas?

Saludos!

**Comment by Hernan4444** [comment]
Elije la atracción con entrada más cara entre las que no tiene. Solo puede tener una atracción de cada tipo.

Saludos ✌️
