### ISSUE TITLE
Duplicar costo de Entrada

### ISSUE THREAD

**Issue by duncanclassic** [IIC2115/Syllabus-2018-1#104]
Me esta pasando que al duplicar por primera vez los precios de las entradas (despues del primer fallo) en el cual tengo 200.000HC aprox y pierdo 340.000 HC por lo que quedo con saldo negativo, luego al siguiente minuto, aun tengo saldo menor a 100.000, por lo que se vuelve a duplicar y asi constantemente hasta terminar con precios ridiculos y nunca recuperar dinero ya que todos se van porque las entradas quedan muy caras.

Luego de una duplicacion, se espera un tiempo apropiado para recuperarse antes de volver a duplicar los precios? En el enunciado no lo dice. 

saludos

**Comment by josetov** [comment]
misma duda que @duncanclassic, de hecho me pasa esto mismo en las 2 simulaciones que nos piden

**Comment by duncanclassic** [comment]
@josetov  del grafico del enunciado se podria entender que solo se vuelve a duplicar cuando vuele a pasar de 100.000 para abajo, sino no tendria sentido, alfinal lo asumi asi y la simulacion funciona bien
