### ISSUE TITLE
[Tarea 1]

### ISSUE THREAD

**Issue by isidorapalmap** [IIC2115/Syllabus-2018-1#107]
Hola! No me queda claro el minuto en el que comienzan a funcionar las atracciones ni cuanto se demoran entre una vuelta y otra. ¿Comienzan las tres del principio a funcionar en t=1? ¿Cuánto es el tiempo que demoran en cargar a los pasajeros? Gracias!

**Comment by Hernan4444** [comment]
@isidorapalmap si la simulación parte en el tiempo 1, en ese mismo tiempo todas las atracciones parten funcionando. Dentro de la base de datos que subimos, se indica el tiempo que toma cada atracción de dar una vuelta, luego de ese tiempo, las personas se bajan, suben nuevas y empieza la siguiente. Salen y suben en el mismo minuto.

Por ejemplo, si la atracción dura 10 minutos y empezó a andar en el minuto 1. Entonces en el minuto 11 salen todos los que estaban adentro, se van a otra atracción y entran todos los posibles que estaban en la cola. Y en ese minuto vuelve a empezar, de modo que en el minuto 12, la atracción ya lleva 1 minuto de vuelta.

Espero responder tu duda.
Saludos ✌️

**Comment by isidorapalmap** [comment]
Perfecto, muchas gracias!
