### ISSUE TITLE
FALLA ATRACCIÓN CLIENTE 100

### ISSUE THREAD

**Issue by svigneaux** [IIC2115/Syllabus-2018-1#108]
Si a una atracción le faltan 2 personas para llegar a las 100 vueltas y en la próxima vuelta le toca a 4 personas subirse: la atracción igual da esa vuelta y falla después de la vuelta? O falla antes de la vuelta?

**Comment by Hernan4444** [comment]
@svigneaux falla en esa vuelta, con esas 4 personas dentro. (Recuerda que falla junto con personas dentro para que puedan demandar al dueño). Lo que sí, queda a tu criterio en que minuto durante la vuelta decides que falle, en el minuto 1, 2, último, etc. Solo asegura que esas 4 personas terminen demandando al dueño.

Espero haber respondido tu duda.
Saludos ✌️
