### ISSUE TITLE
Logs solicitados en T01

### ISSUE THREAD

**Issue by aeavalos** [IIC2115/Syllabus-2018-1#109]
Con los Logs que se solicitan en el enunciado de la tarea, se refieren a que debo almacenar esa información en un archivo tipo .log? O que se debe mostrar en la pantalla cada vez que algo así sucede?

Desde ya muchas gracias 😄

**Comment by Hernan4444** [comment]
@aeavalos sedebe mostrar en pantalla (`print`)
Saludos ✌️
