### ISSUE TITLE
[T01] Librerías

### ISSUE THREAD

**Issue by isalvador95** [IIC2115/Syllabus-2018-1#11]
Qué librerías puedo importar a mi código para utilizarlas en la tarea? La que yo quiera o me van a penalizar si utilizo algo que no se enseñó en el curso?

**Comment by Hernan4444** [comment]
@isalvador95,  para el uso de una librería, tienes que indicarnos el nombre de esta y para que la ocuparás. De este modo nosotros evaluaremos si la permitimos o no según lo que esperámos de esta tarea

**Comment by inavarro1** [comment]
¿Puedo usar la librería "os" para hacer la consola?

**Comment by fnquinteros** [comment]
@inavarro4 podrías especificar qué funciones de la librería planeas usar y para qué?  (sin subir código) por favor :)

**Comment by inavarro1** [comment]
quiero usar la función que limpia la pantalla y muestra el menu nuevamente

**Comment by fnquinteros** [comment]
Okey :) no hay problema.
