### ISSUE TITLE
USO DE HERENCIA

### ISSUE THREAD

**Issue by svigneaux** [IIC2115/Syllabus-2018-1#110]
Para la resolución de la tarea, ¿debemos usar toda la meteria vista? Hasta ahora, no he usado herencia en mi código, será necesario incluirlo para efectos de la revisión de la tarea?

**Comment by Hernan4444** [comment]
@svigneaux el objetivo de la tarea es evaluar que sepan aplicar los contenidos en clases cuando corresponde, así que no puedo decirte si es necesario o no.

Saludos ✌️
