### ISSUE TITLE
Diagrama de clase

### ISSUE THREAD

**Issue by ignaciacunich** [IIC2115/Syllabus-2018-1#113]
Al poner los atributos en un diagrama de clases, ¿se deben poner solo los que están en el paréntesis del __init__, es decir, los que se dan al instanciar el objeto?

Por ejemplo, en la siguiente clase ¿se debería poner también la cola y el andando o no? :
class Atracciones:
    def __init__(self, nombre):
        self.nombre = nombre
        self.cola = deque()
        self.andando = False

**Comment by ignaciacunich** [comment]
Y respecto a los métodos, si el método no retorna nada, solo hace print y llama a otros métodos, ¿En el diagrama de clases, al escribir el método, se pone +nombre(parámetros): None?

**Comment by Hernan4444** [comment]
Hola, sobre lo primero, se ponen todos los atributos, en este caso tambien cola y andando. 
Si un método no retorna nada se hace como indicaste +nombre(parámetros): None

Saludos ✌️
