### ISSUE TITLE
Problema de dinero para Antonio [T01]

### ISSUE THREAD

**Issue by aeavalos** [IIC2115/Syllabus-2018-1#114]
No sé si será por un error en mi programa, pero cuando corro la simulación ocurre que al fallar la primera, Antonio cae en la "quiebra" porque no alcanzó a acumular suficiente dinero con las vueltas, las entradas son muy baratas aparentemente. Por lo que cae en un súper loop donde está duplicando los costos de las entradas a los juegos en cada minuto, por lo que nadie entra a los juegos. (Utilizando los datos de CONSTANTES_INFORME.py)
Es esto posible o mi programa tiene un error? 🤔 

Desde ya muchas gracias 😄

**Comment by Hernan4444** [comment]
@aeavalos recuerda que Antonio solo duplica los precios cuando pasa de tener más de 100.000 a menos de 100.000, si se mantiene siempre con menos de 100.000, entonces solo duplicaría una vez (la ocasión que bajó) y no duplica nuevamente. 

Ese super loop solo se me ocurre que pasa si es que Antonio tiene menos de 100.000 en un minuto y más de 100.000 en el siguiente y así sucesivamente.

¿Puedes verificar si estás cumpliendo con eso?
Saludos ✌️
