### ISSUE TITLE
Falla de Atracción

### ISSUE THREAD

**Issue by nmayne14** [IIC2115/Syllabus-2018-1#116]
Las atracciones fallan 1 vez en todo el tiempo cuando se sube el visitante nº100, o fallan cada vez que se suben 100 personas?

**Comment by Hernan4444** [comment]
@nmayne14 en teoría, cuando fallan las atracciones y son arregladas luego de 1 hora, comienza de nuevo el conteo, pero como no quedó especificado en el enunciado, queda a tu criterio.

Saludos ✌️
