### ISSUE TITLE
Funcionamiento atracciones

### ISSUE THREAD

**Issue by atpimstein** [IIC2115/Syllabus-2018-1#117]
Quería saber si era correcto suponer que la atracción solo comienza a funcionar cuando hay al menos una persona arriba, ya que parece que había un issue donde decían que funciona aunque no haya nadie, pero me parece un poco sin sentido que si una persona llega a la cola tenga que esperar 5 minutos porque la atracción está funcionando sin nadie sobre ella. Yo ya hice mi modelación bajo este supuesto que me parece bastante razonable, gracias!

**Comment by vickyenberg** [comment]
Hola @atpimstein ! yo pregunte eso en otra issue y no puedes hacer ese supuesto :(

**Comment by Hernan4444** [comment]
@atpimstein tal como dice vicky, no se puede hacer ese supuesto. Auqnue suene agradable, hace 9 días dijimos que no.

Saludos ✌️
