### ISSUE TITLE
DUPLICAR PRECIOS

### ISSUE THREAD

**Issue by svigneaux** [IIC2115/Syllabus-2018-1#118]
El enunciado dice que "cuando el dueño disponga menos de 100.000 HC, duplicará los precios". Esto quiere decir, que en el minuto X, tengo que duplicar los precios porque tengo menos de 100.000; si en el minuto X+1 sigo teniendo menos de 100.000 también duplico los precios. En ese caso, podría tener que duplicar los precios sucesivamente y podrían dispararse infinitamente, con lo que nunca volvería a subirse gente a las atracciones.

**Comment by Hernan4444** [comment]
@svigneaux te faltó leer que dice "según el siguiente diagrama":
![image](https://user-images.githubusercontent.com/15641721/39049657-b9d5a7ea-4478-11e8-875a-6833ac65c1dd.png)

Aquí se muestra que solo en el instante que bajó de los 100.000, se indica que se duplica el precio.

Saludos ✌️
