### ISSUE TITLE
Diagramas de clase informe

### ISSUE THREAD

**Issue by frosati1995** [IIC2115/Syllabus-2018-1#121]
Hola!
Al poner los atributos en un diagrama de clases, ¿se deben poner solo los que están en el paréntesis del init, es decir, los que se dan al instanciar el objeto?

Por ejemplo, en la siguiente clase ¿se debería poner también la cola y el andando o no? :
class Atracciones:
def init(self, nombre):
self.nombre = nombre
self.cola = deque()
self.andando = False

Y respecto a los métodos, si el método no retorna nada, solo hace print y llama a otros métodos, ¿En el diagrama de clases, al escribir el método, se pone +nombre(parámetros): None?
Gracias

**Comment by Hernan4444** [comment]
#113
