### ISSUE TITLE
Herencia en Diagrama de Clase

### ISSUE THREAD

**Issue by ignaciacunich** [IIC2115/Syllabus-2018-1#122]
Hola, ¿si tengo una clase que hereda todos los atributos de otra, en el diagrama dejo en blanco el cuadrito de atributos de la clase que hereda? Otra pregunta, ¿Si algún atributo es una lista se pone :list?

Gracias!

**Comment by Hernan4444** [comment]
@ignaciacunich si, si está heredando, no es necesario repetir sus atributos. 
>  ¿Si algún atributo es una lista se pone :list?

sip, o puedes poner []

Saludos ✌️
