### ISSUE TITLE
Feedback y corrección actividades evaluadas

### ISSUE THREAD

**Issue by cristianhojas** [IIC2115/Syllabus-2018-1#124]
Hola! Se va a avisar cuando sea entregado el feedback de actividades evaluadas (en el caso de que el alumno lo pida)?? Esto para saber cuando empiezan a correr las 24 horas que hay para hacer la corrección. Gracias

**Comment by Hernan4444** [comment]
@cristianhojas se mandará un aviso en cuando se suba el feedback, esto será aproximadamente a las 10AM de hoy y tendrán las 24 horas. 
Saludos ✌️
