### ISSUE TITLE
Inscripción pareja Tarea 2

### ISSUE THREAD

**Issue by aeavalos** [IIC2115/Syllabus-2018-1#125]
Hola, intenté meterme al formulario para inscribir mi pareja para la tarea 2, pero me sale que necesito permiso. 😟 

Desde ya muchas gracias por la ayuda.

**Comment by bamavrakis** [comment]
Hola! Te logueaste con tu cuenta uc para inscribirte?

**Comment by Hernan4444** [comment]
@aeavalos tienes que ingresar al formulario con la cuenta uc. Si tienes múltiples cuentas de google activas, entonces el form está detectando otra y no la UC.
