### ISSUE TITLE
Recorreccion AC04 

### ISSUE THREAD

**Issue by agustincardoen** [IIC2115/Syllabus-2018-1#126]
Hola, quería saber como recorregimos la actividad 4, ya que el form esta inhabilitado para hacerlo, muchas gracias!

**Comment by Hernan4444** [comment]
@agustincardoen tal como dice en #83.
> Espera a que empiece el proceso de recorrección, incluso si recibes el feedback antes. Por Siding se avisará el inicio y cierre del proceso de recorrección para un conjunto de evaluaciones

Todavía no mando dicho aviso.
Saludos.

**Comment by agustincardoen** [comment]
Ok, gracias!
