### ISSUE TITLE
Tarea 2

### ISSUE THREAD

**Issue by penrione1** [IIC2115/Syllabus-2018-1#128]
Estimados,

Es posible utilizar función "eval" para resolver operaciones aritméticas expresadas en un string?
ej. eval("2+1-32")?

Saludos

**Comment by hanavarrete** [comment]
Hola! No. eval() y exec() están prohibidas. Saludos

**Comment by BrunoLertora** [comment]
Y se pueden usar ciclos iterativos de forma explicita para evaluar las expresiones?
