### ISSUE TITLE
usar distintas lineas

### ISSUE THREAD

**Issue by marcelodutilh** [IIC2115/Syllabus-2018-1#13]
hola, a uno le pueden pedir ir de una estacion de la linea 1 a la 3 o son sólo rutas dentro de las mismas lineas las que hay que calcular? que no lo entendi del enunciado. muchas garcias

**Comment by fnquinteros** [comment]
Hola! En el anunciado nunca hacemos referencia a lineas de metro, solo hay conexiones (dadas en el archivo correspondiente) entre metros que, curiosamente, se llaman igual a las estaciones de metro de Santiago. Por lo tanto, no entiendo tu pregunta 😅

**Comment by marcelodutilh** [comment]
no entiendo porque hay 3 modelos, ósea que uno puede obtener_modelo(1) obtener_modelo(2) y obtener_modelo(3).. ósea de que sirven esos? hay que elegir uno de los 3? o están los 3 conectados

**Comment by Hernan4444** [comment]
@marcelodutilh Son 3 modelos distintos, donde se conectan las estaciones de diferentes formas y por lo tanto las rutas para llegar de una estación a otra son distintas y la idea es que tu tarea nos ofrezca la oportunidad de buscar alguna ruta en alguno de los 3 modelos (o en los 3 al mismo tiempo) y a partir de ese resultado realizar una serie de consulta.

**Comment by marcelodutilh** [comment]
ok muchas gracias
