### ISSUE TITLE
[Tarea 2] Pesos 

### ISSUE THREAD

**Issue by Claudiorobles** [IIC2115/Syllabus-2018-1#132]
El valor de la casilla B1 nos da que vale  2. ¿Es este un peso en el arco A1-B1 o peso en el nodo B1? 
Tenemos que trabajar los peso e los arcos o nodos ?

**Comment by paxcema** [comment]
Hola,

Tal como se entiende del material de clases, el valor de la casilla es el costo de transitar por ésta, sin importar el nodo desde el que se venga.

Saludos.
