### ISSUE TITLE
Espacios con letras

### ISSUE THREAD

**Issue by svigneaux** [IIC2115/Syllabus-2018-1#133]
Si un espacio tiene una letra, se debe eliminar ese espacio y correr toda esa fila a la izquierda? O solo eliminar la letra y que ese espacio quede vacío?

**Comment by bamavrakis** [comment]
Hola! Efectivamente, esas letras sobras y deben ser eliminadas, por lo que el resto de la línea se verá desplazada hacia la izquierda.
Saludos!

**Comment by cristianhojas** [comment]
Por enunciado se entiende que cualquier símbolo de los siguientes  !”#$%&()=?, debe ser considerado como un obstáculo en el mapa. Entonces ese espacio debiese quedar con una 'X' ?? Eso es lo que entiendo, pero no sé si es así. Gracias
