### ISSUE TITLE
Funciones para consultas

### ISSUE THREAD

**Issue by SebaVasquez** [IIC2115/Syllabus-2018-1#135]
Estimados,

Las funciones implementadas para las consultas solicitadas también deben ser todas recursivas?

Gracias,

**Comment by hanavarrete** [comment]
Si, para las consultas las funciones deben ser recursivas. Saludos

**Comment by fjmunoz3** [comment]
Hola! Ayer estuve hablando con Bastián y Pato y me dijeron que no era necesario que fueran recursivas (o al menos el BFS),  mientras se cumpliera el orden requerido. Me quedo con eso?

Saludos

**Comment by paxcema** [comment]
Hola! Lamentablemente, no, porque contradice la respuesta de @hanavarrete, previa a la ayudantía.

Saludos
