### ISSUE TITLE
[Tarea 2] While, For

### ISSUE THREAD

**Issue by rporellanar** [IIC2115/Syllabus-2018-1#136]
Para la primera parte (eliminar letras, hacer las operaciones y colocar X) se pueden utilizar for o while. ¿O es toda la tarea con programación funcional?

**Comment by hanavarrete** [comment]
Tal como dice el enunciado, solo para esa parte se debe usar programación funcional. Las otras restricciones se encuentran en cada apartado, y la de las consultas recursivas (solo recursivas, no iterativas) en la introducción. Saludos!

**Comment by josetov** [comment]
@hanavarrete  Cuando hablan de guardar el mapa, ¿se debe exportar este a un nuevo .txt? ¿puede esta exportación usar for y while? 
Pregunto porque el pre-procesamiento lo hice entero de forma funcional y lo guarde en una list(), y al momento de escribirlo en un .txt, itero sobre esta lista usando if's y varios criterios mas.

**Comment by jsmeby9** [comment]
@hanavarrete tengo la misma duda que @josetov ,¿Se puede ocupar for en la exportación?

**Comment by fnquinteros** [comment]
Hola! No deben usar for ni while para escribir el archivo. Piensen una forma de escribirlo todo de una. Saludos!
