### ISSUE TITLE
[Feedback AC05]

### ISSUE THREAD

**Issue by josetov** [IIC2115/Syllabus-2018-1#137]
Donde puedo solicitar mi feedback de la AC05, en siding solo hay un cuestionario para la AC06 y aparezco sin participación en esa, aun cuando mande código e hice el control de esa clase.

Gracias!

**Comment by Hernan4444** [comment]
Hola, no hya feedback individual de la AC05. Si estuviste presente en clases y entregaste un código, manda una recorrección indicando eso y cuando termine el periodo de recorrección, revisaré tu caso y responderé con el resultado de la recorrección
Saludos :v:
