### ISSUE TITLE
[Tarea 2] Representación del grafo

### ISSUE THREAD

**Issue by IAndy10** [IIC2115/Syllabus-2018-1#138]
Hola. ¿Qué estructura de datos recomiendan usar para construir el grafo? Gracias 💯

**Comment by duncanclassic** [comment]
En el material de clases se usa una clase grafo pero los vecinos se almacenan en una lista de adyacencia, y segun el enunciado no se pueden usar ni listas de adyacencia ni matrices, entonces como almacenamos la informacion de los vecinos?
