### ISSUE TITLE
[Tarea 2] Mapa resultante

### ISSUE THREAD

**Issue by frosati1995** [IIC2115/Syllabus-2018-1#139]
Esta bien que el mapa no sea cuadrado ni rectangular? 
Si esto esta bien los espacios sobrantes son 0 o X?

**Comment by fnquinteros** [comment]
Debería ser rectangular o cuadrado, el mapa que les pasamos esta malo, pero pueden escribir un txt ustedes con un mapa rectangular para probar el programa siguiendo las restricciones del enunciado. De todas formas nosotros evaluaremos con uno rectangular nuevo. Saludos!

**Comment by frosati1995** [comment]
Como puede ser cuadrado si por ejemplo las dos primeras filas de el mapa son

H,O,L,A,!,2,5+4,?,3,5,15,X,%
F,E,L,I,P,E,W,A,S,H,E,R,E,3,7,&,5+3,4,X,4

si solo se quedan las celdas que tienen signos , x o numeros la primera fila tiene 9 elementos utiles y la segunda tiene 7 elementos utiles .
