### ISSUE TITLE
T02 [mapa no rectangular]

### ISSUE THREAD

**Issue by ignaciacunich** [IIC2115/Syllabus-2018-1#140]
El mapa resultante no es rectangular porque están son las dos primeras filas:
H,O,L,A,!,2,5+4,?,3,5,15,X,%
F,E,L,I,P,E,W,A,S,H,E,R,E,3,7,&,5+3,4,X,4
haciendo lo que se pide en el enunciado la primera fila queda con 9 y la segunda con 7.

**Comment by fnquinteros** [comment]
Esta pregunta ya fue respondida en otra issue (#139) Saludos!
