### ISSUE TITLE
posibilidad de solicitar feedback atrasado

### ISSUE THREAD

**Issue by jmundurraga** [IIC2115/Syllabus-2018-1#142]
hola se me olvido solicitar el feedback de la actividad 6, existe la posibilidad de poder pedirlo atrasado??

**Comment by sebusquets** [comment]
Me sumo a la pregunta, iba a hacerlo hoy y después me dí cuenta que el plazo había cerrado

**Comment by Hernan4444** [comment]
Hola, al final siempre les daremos el feedback (les debió haber llegado el de la AC06), pero lo que tendrá plazo es el tiempo para indicar que quieren arreglar su actividad.
