### ISSUE TITLE
[T02] Espacios vacíos en mapa

### ISSUE THREAD

**Issue by ignaciacunich** [IIC2115/Syllabus-2018-1#144]
En el enunciado dice esto:
"Un vehículo puede moverse entre espacios vacíos, incluso si el camino entre dos espacios vacíos está en diagonal"
pero, ¿qué espacios vacíos? porque se supone que las letras se eliminan.

¿O debemos completar el mapa con ceros o espacios vacíos para que quede rectangular?

Gracias.

**Comment by fnquinteros** [comment]
Por espacios vacíos nos referimos a casillas válidas con pesos, que no contengan obstáculos. Saludos!
