### ISSUE TITLE
Obstaculo mas cercano [Tarea 2]

### ISSUE THREAD

**Issue by alfredotampe** [IIC2115/Syllabus-2018-1#148]
Al considerar el obstáculo mas cercano, una distancia en diagonal es mayor que una en vertical y horizontal? O simplemente consideramos que ser vecino (considerando los 8 movimientos) es igual en términos de distancia. 
Por otro lado, si existe mas de un obstáculo a la misma distancia, el output debe entregar las coordenadas de todos los nodos que estén a la mínima distancia?

Gracias!

**Comment by hanavarrete** [comment]
Solo consideren que sea vecino. Si hay empate, entrega cualquiera. Saludos!
