### ISSUE TITLE
T02: Heurísticas

### ISSUE THREAD

**Issue by ignaciacunich** [IIC2115/Syllabus-2018-1#149]
Tengo una duda respecto a las heurísticas. 

Cuando me piden calcular la ruta óptima con distintas heurísticas, lo que tengo entendido es que la heurística (por ejemplo, Manhattan) es solo para el cálculo del h en el algoritmo ( A* ) pero no implica que en mi ruta me tenga que ir moviendo de forma Manhattan. ¿Está bien esto?

**Comment by bamavrakis** [comment]
Exacto, la idea de usar la heurística es tratar de estimar la distancia desde un nodo hasta el nodo objetivo, pero no significa que la ruta final que escojas sea necesariamente igual al camino formado considerando solo la heurística.
Saludos!

**Comment by ignaciacunich** [comment]
Ya muchas gracias!! Pero con respecto a lo que dices de "la idea de usar la heurística es tratar de estimar la distancia desde un nodo hasta el nodo objetivo", yo tengo entendido por lo que investigué que la idea del H es que es el COSTO estimado de llegar al nodo destino. Por lo tanto, mi valor h que se calcula con las distintas heurísticas no es una distancia sino que es el costo de llegar de un nodo en particular al nodo de destino moviéndome de cierta forma.

**Comment by ignaciacunich** [comment]
Luego para tener F sumo el costo G y H, no tendría sentido sumar un costo G con una distancia H.
