### ISSUE TITLE
Tarea01-  Rutas

### ISSUE THREAD

**Issue by ndschnitzler** [IIC2115/Syllabus-2018-1#15]
Hola! Cuando uno debe definir una ruta entre dos estaciones, se debe solicitar las dos estaciones a conectar y el modelo que se usara verdad?
El enunciado solo habla de las estaciones. 
Gracias!

**Comment by Hernan4444** [comment]
@ndschnitzler esa es parte de como decidas realizar la consola de tu tarea. Puedes pedir el modelo o hacer la consulta en los 3 modelos al mismo tiempo.  Queda a tu criterio.

Saludos!!
