### ISSUE TITLE
Como calcular H

### ISSUE THREAD

**Issue by alfredotampe** [IIC2115/Syllabus-2018-1#151]
Al momento de calcular H (F=G+H), la heurística tanto de Manhattan como de Euclídes solo consideran la distancia geométrica de ir del destino al origen pero no consideran ningún costo asociado a esta distancia (el grafo tiene costos asociados). Es por esto que nuestro algoritmo podría elegir irse en una dirección poco razonable ya que el costo (numérico) de esa celda a la que estamos pasando podría ser muy baja en comparación al resto de los nodos vecinos. Como estamos viendo desde un nodo a sus vecinos, el H va a ser relativamente similar en todos los nodos vecinos ya que no es mucho lo que me acerco o me alejo geométricamente del destino en un iteración. Es por esto que el G+H en algunos casos va a estar prácticamente determinado por quien tiene el G más chico, es decir el costo numérico más chico. En ese caso, podría elegir una dirección poco coherente con la posición del destino.

**Comment by bamavrakis** [comment]
Hola,
Es verdad lo que dices, y esperable. A fin de cuentas A* encontrará la ruta óptima considerando el costo real (del grafo). Justifiquen lo observado y no habrá problemas.
