### ISSUE TITLE
Atorado en un sector del mapa

### ISSUE THREAD

**Issue by atpimstein** [IIC2115/Syllabus-2018-1#153]
Si siguiendo el algoritmo llego a un punto desde el cual no puedo seguir avanzando, debo devolverme y buscar otro camino? Porque al irme por la que parece la ruta más barata puede que no pueda llegar al nodo de destino, mientras que por otra ruta sí podría

**Comment by bamavrakis** [comment]
Hola! La idea es que si te quedas atorado en la búsqueda del camino más barato, el algoritmo siga explorando otros caminos hacia el nodo objetivo. Este gif muestra lo que te quiero decir gráficamente: 

https://upload.wikimedia.org/wikipedia/commons/5/5d/Astar_progress_animation.gif

Saludos!
