### ISSUE TITLE
Uso "explícito" de listas de adyacencia

### ISSUE THREAD

**Issue by fjmunoz3** [IIC2115/Syllabus-2018-1#154]
Hola, a qué ser refiere finalmente esto?
Es válido crear una clase "Grafo" en el que los nodos estén indexados dentro de ésta? (Esto es lo que se hace en el material de clases, donde un atributo  de la clase es una lista de adyacencia)

Por uso explícito de listas de adyacencia se entiende que el grafo en sí sea una matriz?

La pregunta va sobre todo porque al momento de ingresar el input sería óptimo acceder a los nodos directamente (por índice) en vez de hacer otra búsqueda para encontrarlos.

Saludos

**Comment by paxcema** [comment]
Hola,

Por uso explícito se entiende que tienes acceso inmediato a cualquier nodo gracias a la forma en que guardas tu grafo. Esto no está permitido.

Para lograr adyacencia de manera "implícita", se pide que para llegar de un nodo al otro tu programa deba recorrer todo nodo vecino que pase por un camino entre ambos.

**Comment by fjmunoz3** [comment]
Claro,el tema es que para partir del punto de partida que me dan, debería poder acceder directamente a él para poder entonces buscar un camino hacia el punto de llegada (recorriendo como dices).

De lo contrario pareciera que tenemos que hacer una búsqueda para encontrar el punto de partida, además de las búsquedas que ya se nos piden...
