### ISSUE TITLE
Costos de Rutas

### ISSUE THREAD

**Issue by agustincardoen** [IIC2115/Syllabus-2018-1#155]
Hola!

Tengo una duda. Desde mi punto de vista, el uso de las heurísticas no debiese porque cambiar la elección de la ruta óptima, ya que ésta se calcula en base costos y lo que está haciendo la heurística es trabajar con las distancias entre nodos. Por lo tanto, si tenemos nuestro algoritmo A* implementado con distintas heurísticas, la única diferencia va a ser que VAN A IR VISITANDO LOS NODOS DE DISTINTA MANERA, pero tengo entendido que visitar un nodo NO necesariamente significa incluirlo en la ruta optima. Por lo tanto, al reconstruir el camino optimo, A* va a trabajar con los costos de todos los nodos visitados y va a arrojar el mismo camino optimo que tenga menor costo, independiente de los nodos que se hayan visitado en la búsqueda. ¿Es así?
¿Sino, cual sería el beneficio de utilizar una heurística sobre la otra, si con una no estamos encontrando la ruta óptima y estamos pasando por nodos caros?

**Comment by cpamengual** [comment]
Hola! En su minuto yo pensé lo mismo pero las rutas pueden cambiar dependiendo de l heuristica en el sentido de las direcciones en que se puede mover. 

Por ejemplo Manhattan Simple permite 4D (Norte, Sur, este, oeste) pero Euclidiana permite movimiento en 8D (las 4 de Manhattan más las 4 diagonales) así que la ruta puede variar. 

Por ejemplo para ir de A0 a B1 con Manhattan la ruta puede ser A0->A1->B1 mientras que la óptima con Euclides puede ser A0->B1

**Comment by agustincardoen** [comment]
Hola Cami, pero en la ayudantía dijeron que los movimientos no tienen nada que ver con las heurísticas (que calculan el costo asociado de llegar al destino en base a esos movimientos restrictivos que mencionas, 4D y 8D). Pero que en ambos casos, el vehículo se puede mover en las 8 direcciones :( porque así están definidos sus vecinos.

**Comment by bamavrakis** [comment]
@agustincardoen Para tu primera pregunta, tienes razón. Si las heurísticas utilizadas son admisibles, entonces la ruta óptima debería ser la misma para todas las heurísticas utilizadas, y lo único que cambiaría sería la forma en la que se recorren los nodos al momento de buscar esa ruta óptima. Para lo segundo, el "beneficio" del diferente uso de heurísticas es poder ver la diferencia de rendimiento entre ellas, aunque al final encuentres la misma ruta óptima.

**Comment by paxcema** [comment]
@cpamengual Efectivamente lo que dice @agustincardoen es correcto. La heurística estima el costo faltante para llegar al objetivo, pero no dice nada de cómo puedo moverme para llegar a éste. El movimiento sobre el mapa es en 8 direcciones.

**Comment by BrunoLertora** [comment]
@bamavrakis @pcerdam  Pero A estrella no debería retroceder, o sí?. Lo que yo tengo entendido a partir del material de clases, es que la heurística decide cual es el siguiente vecino a visitar según el costo acumulado hasta el nodo (Gn) y la distancia estimada al destino según la heurística (Hn). Esto puede, o no, calzar con la ruta óptima.

**Comment by paxcema** [comment]
@BrunoLertora Correcto. En estricto rigor A* nunca "retrocede". Simplemente explora los nodos expandiendo en el orden que sugiere la heurística (además del costo real actual), y cuando logra llegar al objetivo colapsa la mejor ruta.

**Comment by agustincardoen** [comment]
@bamavrakis @pcerdam Gracias!
@BrunoLertora No es que retroceda, es que en base a todos los nodos visitados reconstruirá el camino a través de los que tengan menor costo. Y se utilice la heurística que se utilice, los nodos que conforman la ruta optima igual van a estar dentro del conjunto de nodos visitados.

**Comment by agustincardoen** [comment]
@BrunoLertora a pesar de que los conjuntos de nodos visitados sean distintos para la implementación de distintas heurísticas.

**Comment by BrunoLertora** [comment]
@pcerdam Y que pasa si se queda atascado? O sea, por las decisiones tomadas en base a la heuristica (que no toma en cuenta "costos" de movimiento) llega a un punto en que sus vecinos son obstáculos y/o nodos ya visitados?

**Comment by paxcema** [comment]
@BrunoLertora Puedes pensar en que se trabaja con una frontera de nuevos nodos candidatos a visitar en el siguiente movimiento. Si se queda "atascado", simplemente elige un nodo que lleve al mejor camino candidato posible. Este nodo puede, eventualmente, estar muy lejos del lugar que atasca al camino del nodo original.
