### ISSUE TITLE
T02 commit

### ISSUE THREAD

**Issue by frosati1995** [IIC2115/Syllabus-2018-1#158]
Hola! me equivoque en hacer el commit en vez de poner T02 puse T01 , importa esto? o como puedo cambiarlo?

**Comment by Hernan4444** [comment]
@frosati1995 no importa el nombre del commit, eso es solo para darle un identificador visual para ti de que se trata el commit. Para cambiarlo, tendrías que eliminar ese commit y hacer uno nuevo, pero reitero que para efectos de este curso, no importa.
