### ISSUE TITLE
Informe T01

### ISSUE THREAD

**Issue by rtrucco** [IIC2115/Syllabus-2018-1#16]
Hola! ¿En el informe qué hay que incluir? ¿Sólo la forma de usar la consola del programa o una explicación del código? ¿En el informe se debe incluir el código como anexo o basta con enviar el .ipynb?

Saludos!

**Comment by Hernan4444** [comment]
@rtrucco lo más importante es que sea la forma de como usar la consola. Si crees que agregar una explicación del código ayudaría al ayudante en algún aspecto, puedes agregarlo 👍. Y basta con subir el .ipynb separado del informe.

Saludos

**Comment by fomorales** [comment]
En la carpeta Tareas se recomienda además subir un readme.md, en este caso sería necesario hacer el readme.md o con el informe basta?

**Comment by Hernan4444** [comment]
@fomorales en este caso, como trabajamos con jupyter notebook, los comentarios pueden ir ahí o en el informe.

Saludos
