### ISSUE TITLE
Template Informe T01

### ISSUE THREAD

**Issue by jtlafuente** [IIC2115/Syllabus-2018-1#17]
Hola, 
El template de latex que subieron tiene como título de documento "Tarea 2" en vez de "Tarea 1".
No sé cómo cambiarlo, porque creo que tendría que editar el archivo MD_estilo.sty (?)
Saludos

**Comment by Hernan4444** [comment]
@jtlafuente error nuestro, tienes que editar el MD_estilo

Saludos

**Comment by rtrucco** [comment]
Se puede usar otra portada en latex o tenemos que si o si usar ese template?

**Comment by Hernan4444** [comment]
@rtrucco puedes usar otra portada 👍 

Saludos!
