### ISSUE TITLE
[Tarea 1][5 Consultas]

### ISSUE THREAD

**Issue by mavaldivia** [IIC2115/Syllabus-2018-1#18]
Hola.

De las consultas que se pueden usar para el bonus, ¿se puede escoger solo una de ellas?.
Porque digamos que si hago la cuarta(la del ranking), también tendría la segunda y la tercera(las rutas mas cortas y más largas). Con estas tres consultas, más la del número de transbordos y la velocidad promedio ¿Estarían bien las cinco consultas?

Gracias

**Comment by Hernan4444** [comment]
@mavaldivia si, puedes escoger solo 1 de esas consultas pero no tendrías tanto bonus como el caso de alguien que use las 3 consultas para hacer bonus. Aunque si haces la ultima consulta, de forma indirecta estás haciendo las otras 2 consultas así que ahí lograrías las 3 consultas. Pero te sugiero que igual permitas utilizar la consulta 2 o 3 mediante el menú (por si queremos conseguir solo 1 ruta).

Saludos
