### ISSUE TITLE
[T01] Prórroga de la entrega

### ISSUE THREAD

**Issue by jpzepedanunez** [IIC2115/Syllabus-2018-1#19]
Estimad@s espero que estén muy bien, los molesto para preguntar si es posible correr la entrega de la tarea en algunos días. Ya que no creo que exista problemas en cambiar un poco de mis días de descanso para poder dejar una tarea mas elaborada y terminada. Además si hay compañeros que van a salir este fin de semana la pueden entregar antes (sabiendo que la fecha de entrega es para el día jueves). Mientras que los que queremos dedicarles más tiempo lo podamos hacer. 

PD: No pido una semana completa mas, solamente 1 o 2 días mas. 

Saludos cordiales.

**Comment by isalvador95** [comment]
Se sabe algo de esto?? A los de programación avanzada le dieron un día más, ellos también entregaban jueves en la noche y ahora lo hacen viernes..

**Comment by Hernan4444** [comment]
@todos el profesor analizará la petición y, en caso de considerarla, se mandará un anuncio.

Saludos
