### ISSUE TITLE
Problemas con carpeta ICON no permiten trabajar

### ISSUE THREAD

**Issue by cpamengual** [IIC2115/Syllabus-2018-1#195]
Hola. Por alguna razón se me crea una carpeta Icon que es read-only y no me deja borrarla ni quitarle el read-only status en ningún lado. Se me crea cuando estoy trabajando en un proyecto utilizando Pycharm, pero al buscar en la carpeta madre del proyecto en Finder (uso Mac), la carpeta no existe. 

Esto impide que pueda correr correctamente el código ya que me tira el siguiente error:

<img width="1332" alt="screen shot 2018-06-23 at 20 53 52" src="https://user-images.githubusercontent.com/37052754/41814847-99062ec2-7727-11e8-811d-589533494345.png">

He probado con distintas variaciones para poder eliminar la carpeta, que también se crea en algunas carpetas random de tarea4 donde están las carpetas con las fotos de los productos (aceite1, etc). Sin embargo, no hay caso. 

¿Cómo puedo hacerlo para poder borrarlo? Todo lo que sugiere Google, hasta ahora, ha resultado inútil. 

Fotos de cómo se ve la carpeta en el Project Manager en Pycharm:
<img width="282" alt="screen shot 2018-06-23 at 20 55 43" src="https://user-images.githubusercontent.com/37052754/41814862-d2ac17fe-7727-11e8-906e-a2354f1fc2a1.png">

<img width="389" alt="screen shot 2018-06-23 at 20 55 34" src="https://user-images.githubusercontent.com/37052754/41814861-d28e4a58-7727-11e8-88b3-55b94482c5e5.png">

Fotos del error que tira:
<img width="387" alt="screen shot 2018-06-23 at 20 56 31" src="https://user-images.githubusercontent.com/37052754/41814867-edc47676-7727-11e8-9ca3-e4bea849026d.png">

Foto del Finder (donde no existe la carpeta):
<img width="203" alt="screen shot 2018-06-23 at 20 56 57" src="https://user-images.githubusercontent.com/37052754/41814869-fd62c254-7727-11e8-9423-7e3f48293fac.png">

**Comment by fnquinteros** [comment]
Hola! Si estás usando un mac, prueba abrir la consola en la carpeta que contiene a la carpeta de tu proyecto y escribe el siguiente comando:

`sudo chown -R username project`

reemplaza username por el nombre del usuario de tu computador y project por el nombre de la carpeta del proyecto. Esto debería permitirte borrar la carpeta ICON.

**Comment by cpamengual** [comment]
@fnquinteros Gracias por la ayuda.
Lo intenté y me dice que no existe la carpeta (que en este caso, es T04). Intenté cambiando también el directory, y creando un nuevo proyecto (en el Escritorio para que el pathname sea más fácil) y nada. 

<img width="423" alt="screen shot 2018-06-23 at 21 51 17" src="https://user-images.githubusercontent.com/37052754/41815146-9986da4c-772f-11e8-941c-21179ce832f7.png">

**Comment by fnquinteros** [comment]
ejecuta `sudo chown -R camila T04` estando en Desktop

**Comment by cpamengual** [comment]
@fnquinteros Hice eso mismo, y si bien "pareciera" haber borrado la carpeta (ahora en el project se ve distinta), de todas formas tira el mismo error. Esta vez, eso sí, terminal no arrojó errores como "No such file or directory". 

<img width="652" alt="screen shot 2018-06-24 at 17 53 15" src="https://user-images.githubusercontent.com/37052754/41824036-a495e6aa-77d7-11e8-8ea3-5d0220a92670.png">
<img width="330" alt="screen shot 2018-06-24 at 17 54 33" src="https://user-images.githubusercontent.com/37052754/41824037-ad656db4-77d7-11e8-886c-b726e0357042.png">

**Comment by paxcema** [comment]
La otra opción es que modifiques el código de features.py para que ignore esas carpetas.

**Comment by cpamengual** [comment]
@pcerdam @fnquinteros Gracias a los dos, al final haciendo miles de movidas no sé cuál de todas funcionó y ahora corre bien.
