### ISSUE TITLE
Para estar seguro: entrega en T01

### ISSUE THREAD

**Issue by etebrito** [IIC2115/Syllabus-2018-1#21]
Hola, gracias por las respuestas!

En la carpeta T01 del repo debe estar:
- archivo .ipynb
- Informe manual usuario en .pdf
- Zip con todo para el informe en latex (de Overleaf, para mi caso)

¿Esto es lo que tiene que ir cierto? La carpeta llamada T01 y dentro los archivos no tienen un nombre formal más que uno que permita su entendimiento. ¿Sí?

Gracias!

**Comment by Hernan4444** [comment]
@etebrito Eso es todo lo que debe tener y dentro de la carpeta pueden tener el nombre que tu quieras (mientras se entienda).

Saludos :v:
