### ISSUE TITLE
Fecha de termino del curso

### ISSUE THREAD

**Issue by marcelodutilh** [IIC2115/Syllabus-2018-1#23]
Estimado profesor, por motivos personales necesito saber con urgencia cuando es la fecha del examen, ya que como me imagino es la última actividad del curso.
Muchas Gracias

**Comment by Tamarainfante** [comment]
En el buscador de cursos no sale especificado, sin embargo, otro curso con el mismo horario tiene fecha para el Viernes 1 de Diciembre.

**Comment by etebrito** [comment]
finalmente será el 1? alguien sabe si el profe especificó algo?

**Comment by halobel** [comment]
Hola, creo que lo comenté en clases, pero no estoy seguro.
La fecha del examen es efectivamente el 01/12, a las 15:30.
