### ISSUE TITLE
Duda T02 - Enfermedad y archivos de apoyo, y otras

### ISSUE THREAD

**Issue by etebrito** [IIC2115/Syllabus-2018-1#24]
Hola!!

Quería preguntar cuándo subirán los archivos de apoyo para poder modelar el mapa necesario para las consultas pedidas, por favooor. Si bien se puede avanzar...simulando el contenido, no me es claro aún lo difícil que será almacenar los datos desde los archivos externos. Además, no se puede probar aún búsquedas o cosas por el estilo, el mapa "almacenado" :m ... gracias! 
Pido disculpas si lo encuentran innecesario, pero siento que lo es :/ 

Otra cosa, respecto a la enfermedad: las personas están separadas entre contagiad@ y sanos. Me causa demasiada intriga y pena el hecho de notar que, si bien la enfermedad te vuelve extremadamente guapo, nadie pueda verlo porque..también causa ceguera..y están todos los contagiados juntos :/ 

Gracias!!

**Comment by etebrito** [comment]
Otra duda!!!
Para obtener la cantidad de contagiados en T+1, en el término con la sumatoria: tanto los Ci a considerar como la "cantidad de vecinos" son los países que efectivamente pueden contagiarte, no? Es decir, quitando aquellos que no pueden debido a Campos de Fuerza o Cúpula (en ese caso...ninguno jaj).

Gracias!

**Comment by etebrito** [comment]
Otra duda!!
No tengo muy clara la diferencia práctica entre el mapa de contagio y el de viajes. ¿El mapa de viajes tiene puede pasar por más partes aparte de país a país? O también son caminos que van de país a país..solo que de forma más limitada, no?
Por temas de orden, nos piden "modelarlos" de forma separada en el código, cierto? 

Otra cosa! Por el tema del contagio "indirecto", un país que tiene mayor tasa de contagio hará que el país vecino aumente más su cantidad de contagiados (si x>y) ..pero al día siguiente, ese país que fue contagiado por el "foco vecino" contagiará de forma que tanto su nueva tasa Cp y su X(T) dependió del foco vecino  y así, pero no entiendo cómo capturar y conservar es efecto que depende del país "foco", siendo que todos los vecinos estarán contagiando en todos lo días... huele a backtraking o estoy demasiado perdido? 
Tal vez en T=0 hay focos claros y el resto de países sanos, pero de todas maneras llegará un T tal que los nuevos contagiados de un país, dependan de más de un foco...tal vez la complejidad de la consulta es aislar el efecto no?

Saludos!

**Comment by etebrito** [comment]
Una más...la "población viva" cuando se describe a la info que vendrá en los países..es la población sana, cierto? no se muere gente a medida que pasa el tiempo, sólo se contagia, no?

dice que el virus es mortal..pero sólo tenemos info de la propagación..no del momento en que se muere un infectado y se reduce la cantidad de habitantes

graaaaaciaaaas

**Comment by fnquinteros** [comment]
Hola! muchas dudas!!! jajaja vamos a contestarlas todas:

* 1.- Acabamos de subir unos archivos de prueba 😉 No necesariamente se evaluará la Tarea con esos archivos, pero los que usemos tendrán ese mismo formato. Y sí, la enfermedad es bastante despiadada en ese sentido 😞, pero así es la vida, cómicamente trágica 😅.

* 2.- Efectivamente, sólo cuentan los vecinos que pueden contagiarte. No debes considerar ni los vecinos subterráneos ni los que estén "bloqueados".

* 3.- El mapa de viajes indica las rutas que puede seguir un enviado de la ONU. Las conexiones no son necesariamente iguales a las del mapa de contagio y si se cierran conexiones del mapa de contagio, estas no se cierran en el mapa de viajes. Sin embargo, ambos mapas son del mismo mundo, por así decirlo, es decir, ambos tienen los mismos países, en los mismos lugares, con los mismos vecinos. Lo que cambia son las conexiones y su utilidad, por ende, sí, debes modelarlos por separado 😉.

* 4.- Sobre eso, el contagio es día a día y dos o más países pueden contagiar a uno al mismo tiempo, por lo que es recomendable **guardar de alguna forma el contagio** que recibió un país por parte de **cada vecino** en cada día o en un día en específico, así sabes, dado el contagio propagado por un país A, cuánto del total de contagio recibido por el país B fue gracias al país A. Backtracking no creo que sea una solución adecuada, más bien tendrías que simular el estado del mundo en cada día, hasta que se termine la simulación (cuándo no se sigue propagando la enfermedad o cuando todos están enfermos) e ir conservando el contagio propagado en cadena en cada día. No debiera ser muy complicado si guardas la información de contagio bien 😉. Espero que se haya entendido, si no, vuelve a preguntar nomás 😅.

* 5.- Tienes razón, población viva = población sana. Pero si te fijas en los `.csv` que subimos no sale explícito, porque se debe calcular la cantidad de infectados con las funciones proporcionadas. No hay gente muerta, sólo infectada. No lo consideraremos porque la enfermedad no los mata, los mata las ganas de apreciar su nueva belleza frente al espejo y no poder por la ceguera 😕.

Creo haber contestado todo (uff!) jajaj 😅.
Saludos!

**Comment by etebrito** [comment]
jaajjaja muchas graciaaas !!!! me aclaraste mucho!
si surgen dudas pregunto denuevo!

Saludos!

**Comment by ndschnitzler** [comment]
Hola! me queda una duda! Los archivos pueden ir variando? es decir mi programa debe ser capaz de abrir los archivos y trabajar con ellos? Esto implica que no puedo editar los documentos, si no que mi programa tiene que hacerlo?

**Comment by Hernan4444** [comment]
@ndschnitzler lamento la demora (no nos llegó aviso de esta issue 😞 ). No puedes editar los documentos, todo tiene que ser tratado por tu programa
