### ISSUE TITLE
T02 - Mapa de viaje

### ISSUE THREAD

**Issue by mjgomez3** [IIC2115/Syllabus-2018-1#25]
Hola! tengo una duda con respecto al mapa de viaje.
Me imagino que el **mapa de contagio** debe entregar algo de la forma: País A contagia a país B, C y D. (para cada país).
Pero que debería entregar el **mapa de viaje**... La ruta entre dos paises para todos los países?
Saludos y gracias :)

**Comment by Hernan4444** [comment]
@mjgomez3 precisamente el **mapa de viaje** te entrega las rutas entre dos países para todos los países. 
Ps: Ya están subidos los archivos por si acaso.
Saludos ✌️

**Comment by mjgomez3** [comment]
Gracias!
Respecto a el mismo tema, el mapa de contagio va cambiando para cada día T mientras que el mapa de viaje se mantiene constante en el tiempo, estoy bien?

**Comment by fnquinteros** [comment]
Exacto

**Comment by fnquinteros** [comment]
Y ambos comienzan en base al archivo que les entregamos
