### ISSUE TITLE
Orden de infección

### ISSUE THREAD

**Issue by mandrade1** [IIC2115/Syllabus-2018-1#27]
Tengo un par de dudas con el tema de la infección y del enunciado del juego que no logro entender bien

Los países que cuentan con Underground society no pueden contagiarse , es decir se asume que toda la población se encuentra sana y bajo tierrra??

Para la cronología de la infección primero se obtiene el cp de cada país y luego el Ip(T+1)??

Saludos

**Comment by mandrade1** [comment]
si podrían explicar un poco mas detalladamente y cronologicamente  como es el proceso de infección

Saludos

**Comment by fnquinteros** [comment]
Hola! En primer lugar, no. Los países y las sociedades subterráneas son independientes entre sí. De hecho no podríamos considerar que un país tiene una sociedad subterránea, más bien es como si existiera un mundo en la superficie y otro bajo tierra. Con respecto a lo segundo, primero calculas el cp de cada país en el día actual, y para calcular la cantidad de infectados de cada país el día siguiente utilizas la formula entregada, remplazando Ip(T) por la cantidad de infectados (que en el día 0 está dado en un archivo con estados iniciales), cp por lo calculado anteriormente y Sp(T) por la cantidad de gente sana (que obtienes porque conoces el total de población y la cantidad de gente infectada.

Saludos!

**Comment by mandrade1** [comment]
Tengo una duda con respecto a las sociedades subterraneas, de que me sirve que un pais este conectada con una sociedad subterranea?? las sociedades subterraneas no poseen ninguna interaccion con la infeccion o si?

**Comment by mandrade1** [comment]
otra duda, con respecto a la formula de contagio.. el valor que esta en sumatoria de los vecinos son solo las conexiones de entrada verdad, osea solo se consideran los vecinos que contagian a un país A y no los vecinos que el país A contagia??

**Comment by fnquinteros** [comment]
* Sirve para realizar consultas sobre la ruta más sana.

* Como la fórmula indica la cantidad de infectados de un país A, sólo consideras los vecinos que contagian a A.

Saludos!
