### ISSUE TITLE
Duda Tarea 2

### ISSUE THREAD

**Issue by GianfrancoSattui** [IIC2115/Syllabus-2018-1#28]
En las cúpulas para bloquear el contagio, se dice que se utiliza cuando el porcentaje promedio de los países alrededor del país alcanza el 70%. Si ese porcentaje llegase en un tiempo determinado T a 71%, por ejemplo, y se aplicase la cúpula, y en (T+1) llegase a 68%, ¿se retira la cúpula y posteriormente se vuelve a poner y sacar sucesivamente? ¿o se deja para siempre? 
Tengo la misma duda para el campo de fuerza. Una vez que se utiliza, ¿se deja para siempre? 

En la consulta 3, si un país A ha contagiado a otro B, pero en tiempos T posteriores personas del B se sanan, ¿No se descuenta de los contagiados de A a B o si?

**Comment by GianfrancoSattui** [comment]
Otra duda más. Para la cuarta consulta que piden, se debe hacer en el mapa de contagio o no? Si así fuese, se debe hacer para un tiempo T determinado ? Y por último, el destino es un país "x" que determina el usuario. ¿El origen es otro país "y" que también determina el usuario?

**Comment by fnquinteros** [comment]
Hola!

* No se vuelven a abrir las conexiones. Sale muy caro ponerlas como para sacarlas con la probabilidad que haya que volver a ponerlas después 💸😕.

* No se descuenta. Para facilitarles un poco la vida 😅.

* La consulta se debe hacer sobre ambos mapas a la vez. Porque el único por el que se puede mover gente es el de viajes, pero ese no contiene la información de contagio. 

* Se nos pasó poner eso, pero sí, debe ser en un tiempo T.

* El usuario determina ambos países.

Saludos!
