### ISSUE TITLE
Tarea 2: fórmula para cantidad de infectados

### ISSUE THREAD

**Issue by jtlafuente** [IIC2115/Syllabus-2018-1#29]
Hola,
Una duda sobre la fórmula para la cantidad de infectados en un país P en el tiempo T+1. Imaginando un país sin vecinos y con una población de 100 personas completamente sanas, yo supondría que IP(T+1) debería ser 0 para ese país.

Pero utilizando las fórmulas del enunciado, la tasa de propagación del país sería:

(0 - 100) / 100 = -1

Y por lo tanto IP(T+1) sería -1*100 = -100 , en vez de 0. No me hace sentido que en T+1 haya una cantidad negativa de personas infectadas en el país P.

Otra duda, en el archivo "paises.csv", la columna "tasa de infección" es lo mismo que la tasa de propagación mencionada en el enunciado?
Gracias

**Comment by bamavrakis** [comment]
Hola!

Para los casos en los que la población infectada para un país en un momento en particular da negativo, puedes dejarla en 0 ya que como dijiste, no tiene sentido que haya una cantidad negativa de infectado.

Para tu otra duda, efectivamente la tasa de infección corresponde a la tasa de propagación inicial para cada país.

Saludos!

**Comment by jtlafuente** [comment]
Siguiendo con la segunda duda, no me calzan algunos valores de la tasa de infección. Por ejemplo, en T=0, según el archivo paises.csv la tasa para Hanslandia es 0.91. Pero utilizando la fórmula del enunciado, la tasa sería:

(x - y) / z = (1,820,000 - 180,000) / 2,000,000 = 0.82

Cuál tasa se ocupa para T = 0? Gracias

**Comment by fnquinteros** [comment]
Tienes razón, considera válido el valor de la formula, vamos a actualizar el archivo para que no haya confusión. Saludos!

**Comment by marcelodutilh** [comment]
No entiendo de donde sacaste el 180.000 y 1.820.000??

**Comment by jtlafuente** [comment]
Según el archivo "paises.csv", Hanslandia empieza con un 91% de población infectada. Como el total de población es 2 millones, 2 * 0.91 = 1.82 millones están infectados, y 0.18 millones están sanos.

**Comment by marcelodutilh** [comment]
sisi pero la issue que hiciste según yo te confundiste porque una cosa es la tasa de propagación, y otra cosa es el porcentaje de infectados...

0.91 es el porcentaje de infectados
0.82 es la tasa de propagación de hanslandia

**Comment by jtlafuente** [comment]
Es que la primera vez que subieron el archivo paises.csv había una columna que se llamaba tasa de infección, que era distinta de la tasa de propagación. Por eso creé la issue. Ahora editaron el archivo y ya no existe la tasa de infección, solo la de propagación.

**Comment by marcelodutilh** [comment]
ok, que lo vi hoydia por primera vez por eso no entendía gracias!
