### ISSUE TITLE
¿Cómo mandar a recorregir?

### ISSUE THREAD

**Issue by Hernan4444** [IIC2115/Syllabus-2018-1#3]
## ¿Qué puedo recorregir?
**Todo se puede recorregir. Desde Actividades no evaluadas hasta controles, tareas, examen, etc**. Como alumno tienes el derecho a recorregir cualquier evaluación siempre y cuando respetes las reglas impuestas en esta issue.

## ¿Cómo recorrijo una actividad?

**NO SE ACEPTAN CORREOS**. Todas las recorreciones serán via este [Formulario](https://goo.gl/forms/ll2GwR8u1Dk9BjMD3). Las respuesta llegará en forma de comentario en tu issue correspondiente a la evaluación o se creará una nueva si el ayudante lo cree conveniente. 

## ¿Cuándo puedo recorregir?
Espera a que empiece el proceso de recorrección, incluso si recibes el feedback antes. Por **Siding** se avisará el inicio y cierre del proceso de recorrección para un conjunto de evaluaciones. Por ejemplo, el primer periodo será de la AC01 (asistencia) y AC02 (nota). Cualquier recorreccion fuera del plazo será rechazada inmediatamente. 

## Reglas
1.  Antes de mandar a recorregir, verifica la versión descargada de tu evaluación según el commit indicado. Muchas veces se hacen cambios a último momento que no son subidos (no hacen `git push`) y por lo tanto no se consideran. No será excusa decir que hiciste `git commit` a tiempo si no hiciste `push`.

1. Verificar si lo entregado está en la carpeta solicitada. Ej: AC01, T01, etc. En otro caso, el **1.0** se debe a que no entregaron en la carpeta indicada. Para situaciones así, deben arreglar su git para que los archivos estén en la carpeta y mandar a recorregir diciendo: 

> Nos equivocamos y no subimos las cosas donde correspondía, pero ahora ya está todo arreglado.

3. Argumenta cada ítem a recorregir. Generalmente un puntaje no es completo porque no implementaste alguna funcionalidad de la evaluación o porque se cae ante cierto input. **No es argumento decir:** 

> A mí sí me funciona

> El feedback dice que yo no hice tal ítem pero yo sí lo hice

### ¿Cómo mejorar esos argumentos?
> A mí sí me funciona, **pero es porque hay UNA o DOS lineas que modifiqué pero no alcancé a subir**

> El feedback dice que yo no hice tal ítem pero yo sí lo hice, **si revisas la linea X del archivo algo.ipynb y y pones un print('funciona') verás que sí se ejecuta ese grupo de códigos que cumplen lo solicitado en ese ítem**

## ADVERTENCIA ⚠️ 

Al mandar a recorregir, estás aceptando que el ayudante y/o profesor revise nuevamente tu evaluación, por lo que la nota puede subir o bajar. No mandes a recorregir sin motivo alguno.

**Comment by sgmigliaro** [comment]
Donde se retiran y se mandan a recorregir los controles?

**Comment by halobel** [comment]
> Donde se retiran y se mandan a recorregir los controles?

Hola, los controles los tengo en mi oficina. Los voy a llevar nuevamente mañana a clases, o puedes pasar a buscarlos a mi oficina. El plazo vence mañana y el proceso se hace de la misma manera que con las recorrecciones de las actividades y tareas.

**Comment by sgmigliaro** [comment]
Se puede mandar a recorregir el control 2? no han abierto el cuestionario si no me equivoco. Gracias y saludos.

**Comment by Hernan4444** [comment]
@sgmigliaro acabo de abrir el cuestionario . Gracias por avisar

Saludos ✌️

**Comment by sgmigliaro** [comment]
Ya subieron las notas de las recorrecciones del control 2? y cuando estaran listas las notas del ultimo? Gracias y saludos!

**Comment by halobel** [comment]
Hola, ya está todo arriba, incluyendo las recorrecciones.
Saludos
