### ISSUE TITLE
Tarea 2: ruta mas corta?

### ISSUE THREAD

**Issue by sgmigliaro** [IIC2115/Syllabus-2018-1#30]
Cuando se dice que hay que obtener la ruta mas sana y corta, con corta se refiere pasar por la menor cantidad de paises? cumpliendo que cada uno tenga menos de un 20% de infectados. Gracias y saludos.

**Comment by sgmigliaro** [comment]
Y para calcular la ruta minima, suponemos que todos los viajes de un pais a otro tienen la misma distancia? osea seria minimizar la cantidad de viajes entre paises?

**Comment by hanavarrete** [comment]
Más corta si, cuenta como que cada viaje cuesta lo mismo entre cada país. Saludos!

**Comment by sgmigliaro** [comment]
Gracias. Y otra duda, en la consulta de retornar el primer pais en que el X% de su poblacion fue infectada, ese x% es el que se fue infectando o no? ya que por ejemplo Hanslandia parte con un 91% de personas infectadas entonces cuando busco el 1er pais que tenga esa poblacion infectada, me entrega Hanslandia altiro

**Comment by fnquinteros** [comment]
Si tienes más dudas que no estén relacionadas con la primera, por favor has una nueva issue, ya que esto es un foro, no un chat, por lo que la idea es que la información se encuentre ordenada para que todos puedan enterarse sobre las respuestas a sus dudas.

Vamos a conversar sobre esto y te entregamos una respuesta lo antes posible, pero mientras tanto, postealo en otra issue, por favor :)

Saludos!
