### ISSUE TITLE
campo de fuerza o cupula

### ISSUE THREAD

**Issue by mandrade1** [IIC2115/Syllabus-2018-1#31]
que mecanismo ocurre antes???

Por ejemplo si un país A tiene un conexión mayor a lo tolerado y el promedio de tasa de infección de los vecinos es mayor al 70%.. ¿que ocurre primero?
opc 1:  se activa el campo de fuerza, por lo que se elimina la conexión y luego se vuelve a calcular el promedio de las conexiones restantes para ver si se activa el campo de fuerza? 
opc 2: se activa el campo de fuerza instantáneamente quedando todas las conexiones bloqueadas

Saludos

**Comment by hanavarrete** [comment]
la opción 2. Saludos!
