### ISSUE TITLE
T02: Sociedad Subterránea

### ISSUE THREAD

**Issue by jtlafuente** [IIC2115/Syllabus-2018-1#32]
Hola,
en el archivo "conexiones_infección.csv" aparece una conexión entre Hanslandia y Dondeeldiabloperdioelponcho.

Esta última es una sociedad subterránea, por lo que no debería ser contagiada cierto? De ser así, es un error que exista esta conexión de contagio? Por lo que revisé, es la única conexión que contiene a una sociedad subterránea, por eso pienso que podría ser un error.
Gracias y saludos

**Comment by fnquinteros** [comment]
No debería estar, los vamos a cambiar y subir el archivo correcto :)

Saludos!
