### ISSUE TITLE
loop infinito

### ISSUE THREAD

**Issue by mandrade1** [IIC2115/Syllabus-2018-1#33]
al correr el programa me encuentro en un loop infinito, porque dada las formulas entregadas en el enunciado y los poderes.. nunca estan todos los habitantes contagiados para cada uno de los países y tampoco estan todos sanos.. el virus dura por siempre

**Comment by fnquinteros** [comment]
No tienen que simular el desarrollo completo de la situación. Si se fijan en las consultas, todas las que requieren conocer el estado del programa piden un día T,  por lo que solo deben simular los datos hasta cierto día, o piden el primer país que se contagia un x%, en cuyo caso simulan hasta que algún país llega a eso. La simulación no tiene un final definido. Si también quieren agregar la opción de simular hasta que todos se infecten o hasta que ya nadie pueda infectarse, está muy bien, pero no está en el enunciado, por lo que no lleva puntaje 😅 

Saludos!
