### ISSUE TITLE
Consulta3

### ISSUE THREAD

**Issue by GianfrancoSattui** [IIC2115/Syllabus-2018-1#34]
No me queda clara la forma en cómo registrar que un país ha contagiado a otro. Según el enunciado, solo sabemos que los contagiados de un país A dependen de un conjunto de vecinos contagiosos que se dirigen a este país A (y del propio país A también). Si el número de contagiados de un tiempo T a otro tiempo (T+1) aumenta (por ejemplo, en 30 personas infectadas), y para ese tiempo T se tenía a 5 vecinos que lo podían contagiar, ¿cómo sé cuántas de las 30 personas fueron contagiadas por cada vecino ?
Se los agradecería si me lo pueden aclarar. Gracias.

**Comment by fnquinteros** [comment]
Me parece que tu duda fue respondida en esta issue: #24. Cómo guardar el contagio recibido de cada país es una dificultad que esperamos que enfrentes en la tarea. Considera hacer que tu grafo/tus nodos puedan guardar este tipo de información.

Saludos!
