### ISSUE TITLE
[Jupiter] localización de carpetas

### ISSUE THREAD

**Issue by Carlos0C** [IIC2115/Syllabus-2018-1#35]
Me podrían orientar sobre cómo entregar a Jupiter IPython una ruta hacia una carpeta determinada para que éste  abra o guarde archivos ahí dentro? 

Graciasssss !

**Comment by hanavarrete** [comment]
Cuando abras jupyter notebook, muevete hacia el directorio deseado y empieza a trabajar desde ahí. Todo archivo que crees desde tu trabajo se guardará en el lugar de trabajo.

Saludos!

**Comment by Carlos0C** [comment]
Quiero decir, digamos que estoy programando en un .ipynb que se encuentra en la carpeta A. Con este programa, quiero abrir un archivo que se encuentra en carpeta B, para luego guardar algún dato otro archivo en la carpeta C. ¿Cómo podría comunicarle a Jupiter IPython para que se dirija a tales carpetas, teniendo en cuenta que mi programa se encuentra en otro lugar de trabajo?

**Comment by hanavarrete** [comment]
Échale una mirada a la librería os. Con ella puedes conseguir la ruta a un archivo y abrirlo con ella. Avísame como te va con eso 😁

**Comment by Carlos0C** [comment]
Graciass !!!!
