### ISSUE TITLE
T02 - Tasa de infección Cp en países sin infectados - Mala propagación de enfermedad

### ISSUE THREAD

**Issue by etebrito** [IIC2115/Syllabus-2018-1#36]
Hola, para corroborar, la tasa cp es -1 para los países no infectados todavía cierto? Porque tienen 0 infectados y todos sanos. Eso quiere decir, que desde el inicio ejercen cierta influencia sobre los demás "curando" según la fórmula, afectando a sus vecinos).

Resulta que cuando instancio...ningún país sin infectados aumenta su cantidad de infectados porque sus vecinos sanos tienen un cp=-1 y los que infectan tienen, por ejemplo, cp=0.66 ... en la sumatoria del factor que aumenta los infectados en un país sano, debe estar quedando un número negativo..por lo tanto, nunca se infecta.

Resultado: sólo los países inicialmente infectados se infectan un poco más, porque aparte de lo anterior, los países vecinos en cierto puntos los BLOQUEAN con su campo de fuerza...

¿No importa si el comportamiento de la enfermedad es poco interesante?

**Por ejemplo, la consulta de qué país sanó mas gente no funciona bien porque ningún país sanó a nadie en ese escenario.**

Espero que tenga la simulación bien codificada, pero por los valores y funcionamiento de la propagación..sí me hace sentido que ocurra lo que está pasando.

**Del mismo modo, la consulta de contagio directo e indirecto...no me está resultado porque los países contagiados no logran contagiar a nadie. ¿Qué puede estar fallando u.u?**

**Comment by sgmigliaro** [comment]
Me pasa lo mismo, los que parten totalmente sanos nunca se infectan.

**Comment by padelabarra** [comment]
A mi igual :/

**Comment by rtrucco** [comment]
A mi también me pasa lo mismo.

**Comment by fnquinteros** [comment]
Conversamos sobre esta situación y vamos a cambiar la formula (un cambio muy pequeño) para que no ocurra esto y avisaremos por siding para que todos estén al tanto del cambio.
Saludos!

**Comment by fnquinteros** [comment]
Hola! La formula fue modificada. La nueva formula le quita peso a la sanación para calcular la tasa de infección.
Saludos!

**Comment by rtrucco** [comment]
Sigo teniendo el mismo error, los países sanos no se infectan nunca.

Sólo para asegurarme, los países se pueden contagiar por las vías que aparecen en conexiones_infeccion.csv cierto? Siendo el pais1 y pais2 el pais de origen y el pais desde donde se puede contagiar el pais1, respectivamente.

En ese caso, los países que no son subterráneos (y que no se pueden infectar), tienen 13 fuentes de contagio cada uno, por lo que la cantidad de vecinos, obvio, son 13.

El cp de un país inicialmente sano es -0.01. Esto significa que para que un país comience a infectarse, el término (1-cp) * sum(ci)/(100n) debe ser mayor que 0.01, y así la fórmula ip + sp * cp + sp * (1-cp) * suma(ci) / (100n) sea mayor que 0.

Entonces, para que un país sano comience a contagiarse, debería pasar que suma(ci) tiene que ser mayor que 12.87, o sea, que todos sus países vecinos estén casi 100% infectados.

No sé si estoy planteando bien el problema o no, pero me sale eso jajaja.

**Comment by fnquinteros** [comment]
Por el momento, déjenlo así. Vamos a pensar en una solución al problema de la fórmula.
Saludos!

**Comment by etebrito** [comment]
Gracias, es verdad que pareciera que todavía no se propaga muy bien, asumiendo que lo estamos codificando bien jaja... espero que cualquier cambio que decida realizarse sea respecto a la base de datos inicial o algo así..y que se mantenga la consistencia por favoooor! (no agregar o quitar una columna, o no sé..algo que haga cambiar la lectura). Y entonces no respecto a la metodología o consultas.
Probablemente varios, como yo, se planificaron con anticipación para la entrega de la tarea. En mi caso tengo una semana bastante complicada de pruebas y tengo las consultas hechas (suponiendo que están buenas)..sólo que no dan resultados muy interesantes para Sanación Acumulada o el Contagio Dir/Indirecto por ejemplo (el resto sí, aunque igual dependen de la infección en los países: la ruta sana y mínima no se limita mucho porque pocos se contagian..y el primer país en contagiarse hasta cierto nivel de infección no funciona bien si no se contagian mucho...). Si quisiera enviar mi tarea final hoy, me sentiría muy perjudicado si hicieran un cambio muy drástico al enunciado porque me obligaría a meterme a codificar en la semana siendo que las cartas ya se pusieron sobre la mesa.

Pido por favor considerar esto!! Lo digo en la tela jaj! es porque en serio creo que no podemos estar pendientes constantemente de esta tarea, hay que balancear con todas las responsabilidades del semestre.

PD: aunque pareciera que puede arreglarse sólo haciendo que haya más focos que empiecen a infectar..o menor países subterráneos..o subiendo las tolerancias y haciendo que los países focos no partan con %infectados tan alto...no sé jaja u.u

Saludos y gracias denuevo!

**Comment by sgmigliaro** [comment]
Y si cambian la entrega para el fin de semana / lunes? se podria?

**Comment by fnquinteros** [comment]
@etebrito Tranquilo, no vamos a cambiar nada sustancial. Como dices, el cambio bien podría ser de los archivos o de la formula nuevamente (cosa que sea cambiar un número en el código solamente).

@sgmigliaro vamos a conversar sobre eso. 

Por mientras, podrían probar usando el mapa de viajes como mapa de infección también y ver si la propagación es un poco más amigable? 😅 Gracias.

Saludos!
