### ISSUE TITLE
T02: Personas contagiadas y sanadas

### ISSUE THREAD

**Issue by jtlafuente** [IIC2115/Syllabus-2018-1#37]
Para las consultas se necesita saber la cantidad de personas contagiadas y sanadas por cada país. Pero la cantidad de personas contagiadas por un país A, incluye a las personas contagiadas dentro de A y también a los que A contagia en otros países B, C, etc? Lo mismo para los sanados, se incluyen a los sanados dentro de A y también a los que A sana en B, C, etc?
Gracias

**Comment by jtlafuente** [comment]
Ahora que cambiaron el enunciado, y no es posible recuperarse de la enfermedad, qué va a pasar con la consulta "encontrar al país que ha sanado a más gente"?

**Comment by jtlafuente** [comment]
@fnquinteros  Al final cómo tenemos que considerar a las personas sanadas y contagiadas? (ver primer comentario de esta issue)

**Comment by fnquinteros** [comment]
Cuenta para la infección se cuenta en cadena y directamente, como dice la consulta. Para la sanación, cuenta sólo la sanación de A por su parte, no tomes en cuenta los vecinos. 

Saludos!
