### ISSUE TITLE
T02: Tasa de infección y fórmula de infectados

### ISSUE THREAD

**Issue by rtrucco** [IIC2115/Syllabus-2018-1#38]
Hice una pregunta como comentario de otra pregunta, y no sé si les llegan las notificaciones de eso, así que voy a copiar y pegar la pregunta. 

1.- Respecto de la tasa de infección modificada, sigo teniendo el mismo error, los países sanos no se infectan nunca.

Sólo para asegurarme, los países se pueden contagiar por las vías que aparecen en conexiones_infeccion.csv cierto? Siendo el pais1 y pais2 el pais de origen y el pais desde donde se puede contagiar el pais1, respectivamente.

En ese caso, los países que no son subterráneos (y que no se pueden infectar), tienen 13 fuentes de contagio cada uno, por lo que la cantidad de vecinos, obvio, son 13.

El cp de un país inicialmente sano es -0.01. Esto significa que para que un país comience a infectarse, el término (1-cp) * sum(ci)/(100n) debe ser mayor que 0.01, y así la fórmula ip + sp * cp + sp * (1-cp) * suma(ci) / (100n) sea mayor que 0.

Entonces, para que un país sano comience a contagiarse, debería pasar que suma(ci) tiene que ser mayor que 12.87, o sea, que todos sus países vecinos estén casi 100% infectados.

No sé si estoy planteando bien el problema o no, pero me sale eso jajaja.

2.- Tengo otra pregunta. Para calcular la cantidad de contagiados que el país B contagia a A, hay que usar una parte de la fórmula de infectados? sp * (1-cp) * suma(ci) / (100n) en vez de usar suma(ci), usamos sólo (ci), manteniendo el resto de los valores constantes, de esta forma:

infectados de B a A: sp * (1-cp) * c_B / (100 * n)

Gracias!

**Comment by fnquinteros** [comment]
1.- Tienes razón, pero eso depende más de los archivos que les pasemos. ¿Podrías probar usando el mapa de viajes como ambos mapas y ver qué pasa con el contagio?

2.- Me parece más correcto dividir el aporte de todos los vecinos proporcionalmente entre los vecinos, teniendo en cuenta el cp de cada uno. Me explico, el país A tiene a B y C como vecinos. En la formula, sp*(1-cp)*suma(ci)/(100n) da _x_ (que corresponde al total de gente contagiada de A a causa de sus vecinos). Si el cp de B es 0.30 y el de C es 0.10, distribuyo _x_ en la razón 3:1 entre B y C, así obtengo la cantidad de contagiados de A a causa de B y C.

**Comment by rtrucco** [comment]
1.- Si cambio el mapa de infección por el mapa de viajes, pasa lo mismo. El término sp * cp pesa mucho en la fórmula, y cuando el país pone la cúpula o el campo de fuerza, termina infectándose al 100% solo. 

2.- Buenísimo, lo haré así. Gracias!

**Comment by MaximoVillarinoSelman** [comment]
Tengo una dusa respecto al enfoque de dividir el efecto entre los vecinos.
Por ejemplo, puede ser que un país tenga una tasa de infección personal negativa (y se está sanando) y todos sus vecinos tienen una tasa negativa, pero el efecto de los vecinos es menor al efecto propio. En este caso, se dividiría la "sanación" entre los vecinos si ocupáramos el enfoque de dividir según las tasas entre los vecinos y no ocupar el efecto de cada uno.
Quizás lo mejor es comparar el cambio en los infectados y, según si aumenta o baja, distribuir entre los vecinos que pueden sanar (en caso que baje) e infectar (en caso que suba)??
No se si comprnedí bien el enunciado! 
Porfavor avisen que onda, gracias
