### ISSUE TITLE
Paises vecinos

### ISSUE THREAD

**Issue by nmorales1** [IIC2115/Syllabus-2018-1#39]
Para la red de contagio, ¿los países vecinos son los que tienen conexiones aéreas con esos países? Y si es así, y con la cúpula o campos se cierran las rutas aéreas, esos países dejan de ser países vecinos?
También, no se si podrían dar como ejemplo de resultados para los infectados de cada país en algún T, para poder comparar con los resultados que nos dan los programas y ver si está funcionando o no.
Gracias.

**Comment by lfandrighetti** [comment]
En el caso de la Cúpula, ¿el porcentaje promedio de contagiados al rededor del país considera los países con los que el país tiene un campo de fuerza?

**Comment by hanavarrete** [comment]
Los países no dejan de ser vecinos cuando se cierran con cupula, por ende, el porfentaje promedio si considera aquellos que tienen el campo. 

Sobre los  resultados por el momento no subiremos nada.

Saludos!
