### ISSUE TITLE
Sanar

### ISSUE THREAD

**Issue by marcelodutilh** [IIC2115/Syllabus-2018-1#40]
en el enunciado sale: "una vez que cierto individuo se contagia, no puede ser sanado". pero en las preguntas que debemos ser capaces de responder sale "dado un día T país  que ha sanado mas gente"
entonces no logro entender como se responde eso..

**Comment by fnquinteros** [comment]
Ups 🙊 Errata del enunciado. Consideren que si se pueden sanar 😅
