### ISSUE TITLE
Contagio Indirecto

### ISSUE THREAD

**Issue by MaximoVillarinoSelman** [IIC2115/Syllabus-2018-1#42]
Hola, tengo una duda del contagio indirecto.

Es posible guardar el aporte que recibe un país de cada uno de sus vecinos, pero cómo defino si es un contagio indirecto?
Por ejemplo, un país sano que comienza a infectarse, recibe de más de un vecino en cierto período y ahí el contagio es directo. Pero si después este país contagia a otro sano, de cuál de los dos países "foco" proviene la infección?
O habría que cuantificar el último efecto (indirecto) y dividirlo entre los dos "focos" también? Cómo se haría esa división? Con la tasa de infección del período de contagio indirecto o según la tasa con que se contagió al primer país de forma directa??
Quedo atento a la respuesta!! Muchas gracias

**Comment by fnquinteros** [comment]
Hola! Si sabes el contagio que recibio B de A, entonces sabes cuánto es el aporte de A para el contagio de C por parte de B, porque ya que el contagio solo depende de la gente contagiada, sabiendo cuánta gente fue contagiada en un país B por parte de A, también puedes saber cuánto contagio fue traspasado indirectamente a C por culpa de A. ¿Se entiende?
