### ISSUE TITLE
Campos de fuerza

### ISSUE THREAD

**Issue by rtrucco** [IIC2115/Syllabus-2018-1#43]
Cuantos campos de fuerza activados al mismo tiempo puede tener un país? 

Si la enfermedad va creciendo en los países, eventualmente quedan todos bloqueados por los campos de fuerza de sus países vecinos, y finalmente, no se contagian.

Gracias!

**Comment by fnquinteros** [comment]
Todos. Si se activaron todos los campos de fuerza antes que la cúpula, no hay problema.

Saludos!

**Comment by hanavarrete** [comment]
Se pueden tener n campos de fuerza, siendo n la cantidad de fronteras. Saludos!
