### ISSUE TITLE
A star, pregunta ruta mas corta

### ISSUE THREAD

**Issue by marcelodutilh** [IIC2115/Syllabus-2018-1#44]
No he podido encontrar mayor diferencia entre djikstra y A*. si utilizo un código que tengo de Dijkstra que me es más fácil de implementar para encontrar la ruta más corta. ¿ existiría algún tipo de descuento en el puntaje ?
Gracias!

**Comment by fnquinteros** [comment]
Si, hay un descuento considerable por no usar A*.

Saludos!
