### ISSUE TITLE
Dudas enunciado T02

### ISSUE THREAD

**Issue by mavaldivia** [IIC2115/Syllabus-2018-1#45]
Hola, con respecto al enunciado tengo algunas dudas.

1.  En la fórmula de cantidad de infectados, cuando dice "cantidad de vecinos" esto considera ¿Vecinos conectados por el mapa de contagio?¿Solo vecinos que estén en la surface?¿Solo vecinos que no estén con campos de fuerza?

2. No me queda nada claro la utilidad del mapa de viaje

Gracias

**Comment by fnquinteros** [comment]
Hola! 

1.- Lo siento, no lo dejamos claro. Se refiere a los vecinos que aportan infección, es decir, los que no esten bloqueados por campos de fuerza/cúpula y no sean subterráneos.

2.- El mapa de viaje es para la consulta de viaje. Un agente de la ONU solo puede moverse a través de las conexiones de ese mapa, y al cerrarse conexiones del mapa de infección, estas NO deberían bloquearse en el mapa de viajes.

Saludos!
