### ISSUE TITLE
Cómo modelar el tiempo? 

### ISSUE THREAD

**Issue by idmdvan** [IIC2115/Syllabus-2018-1#47]
Hola!

En el desarrollo de la tarea, me encontré con una duda que pienso que podría cambiarla sustancialmente, así que quisiera pedir un poco de ayuda sobre cómo piensan que debemos modelar el tiempo. Podría ser sencillamente una variable que se vaya iterando y sobrescriba los datos de la enfermedad de cada país, pero también podría ser toda una clase, pero también podría ser un atributo - método de la clase país... Si depronto pudieran guiarnos con alguna idea sobre cuál es la mejor manera, estaría muy agradecido. 

Gracias!

**Comment by fnquinteros** [comment]
Eso es algo que tu debes pensar, no podemos decirte cómo modelar la tarea 😅 Modélalo como estimes más conveniente.

Saludos!
