### ISSUE TITLE
Ruta mas corta

### ISSUE THREAD

**Issue by marcelodutilh** [IIC2115/Syllabus-2018-1#48]
para la ruta mas corta, las vías para transitar son las del mapa de viaje de los de la ONU verdad? y dentro de estos dejar solo aquellos que tienen una tasa de contagio menor al 20% de contagio?
y se puede partir de un pais que su tasa de contagio es mayor al 20%? por ejemplo ir de Hanslandia a Chile?
la duda me entro porque es cierto que uno puede ir en ese mapa de cualquier punto a cualquier otro. sin embargo cuando se implementa el filtro de tasa de contagio menor a 20% ya no se puede ir de cualquiera a cualquiera. 
queria estar seguro de que esa es la forma de hacerlo gracias.

**Comment by fnquinteros** [comment]
Si no existe la ruta, retorna None e imprime que no se ha encontrado una ruta sana. Esto debe ocurrir también si el país inicial o final tienen más de un 20% de contagio. Por último, no está bien modelado el problema si eliminas los países con más de 20% de contagio. La idea no es que filtres, es que utilices el algoritmo de A* con una heurística que te permita realizar la consulta de forma eficiente. 

Saludos!
