### ISSUE TITLE
Problema Propuesto Arboles y Grafos

### ISSUE THREAD

**Issue by Hernan4444** [IIC2115/Syllabus-2018-1#5]
Para esta semana el ejercicio propuesto está en este [link](https://github.com/IIC2233-2016-02/Syllabus/blob/master/Actividades/AC04/Enunciado%20AC04.pdf)

Esta issue quedará para cualquier duda que tengan del ejercicio y pueden publicar el código que quieran sobre este ejercicio.

Exito!! 👍

**Comment by etebrito** [comment]
hola!
una duda, cuando se pide que se debe usar una estructura de datos propia y que está prohibido utilizar list, diccionarios, etc..es básicamente que el grafo debe ser una class Grafo.. que no se puede almacenar la info de nodos y arcos en una lista..?

en esta tarea en ningún momento se puede usar para ningún propósito list, dicc, etc etc ?? tampoco sería válido crear una clase Arco, una clase Nodo y describir el grafo como una lista con elementos arco cuyos atributos permitan describir interacciones?

gracias de antemano!

**Comment by Hernan4444** [comment]
@etebrito precisamente en esa actividad se esperaba que crearan sus propias clases y no usaran las de python. De este modo (en la actividad) cada grafo tenía la información de él y con quien estaba conectado.

En esta tarea no pusimos esa restricción pero si revisas los objetivos de la tarea, nosotros esperamos que modelen el problema utilizando estructuras adecuadas. Si solo usas listas, no demostrarás manejo de todos los contenidos y eso se verá reflajado en la evalución que hagamos de tu tarea.

Saludos!

**Comment by etebrito** [comment]
Gracias, creo que entiendo! Aunque me causa duda el hecho de que en la materia que subieron se habla de que hay varias formas de representar un grafo. Cuando hablas de sólo usar listas, te refieres a una resolución que no cree ninguna clase? o una solución que modele clases de arcos, nodos, especie, no sé..pero que utilice listas, también entraría en esa categoría. 
Para ser más específico, en los ejemplos de clase de la sesión, el último ejemplo de grafo dirigido..podría ser una referencia para este requerimiento, no? entendiendo que en ningún caso es un copiar pegar jaj me refiero a la "estructura adecuada" :m :m :m ?

**Comment by Hernan4444** [comment]
> Cuando hablas de sólo usar listas, te refieres a una resolución que no cree ninguna clase?

Precisamente, que solo hagas uso de listas para guardar todo cuando puedes tener diferentes clases que ayuden a una mejor modelación.

> una solución que modele clases de arcos, nodos, especie, no sé..pero que utilice listas, también entraría en esa categoría.

Es no entra en la categoríá de usar solo listas. Si utilizas clases y te apoyas de listas para algunas cosas está super bien.

> Para ser más específico, en los ejemplos de clase de la sesión, el último ejemplo de grafo dirigido..podría ser una referencia para este requerimiento, no? entendiendo que en ningún caso es un copiar pegar jaj me refiero a la "estructura adecuada" :m :m :m ?

A veces existe más de una estructura adecuada y todo depende de la forma que analices el problema. Considera que las estaciones están conectadas mutuamente. Si con un grafo dirigido crees poder modelar esa situación, entonces sí, es la estructura adecuada, pero si piensas que tendrán algún problema luego para encontrar las rutas o diversos caminos para un mismo destino, entonces puede ser que el grafo dirigido no sea el indicado o le falte algo más para tener todo lo necesario.

No puedo decirte: "si esta es la estructura" como tampoco puedo decirte "estás mal". Solo puedo decir que vas por buen camino con los grafos 😅 

Saludos!! ✌️

**Comment by etebrito** [comment]
Gracias !
