### ISSUE TITLE
Discusión: Consulta Primeros países en alcanzar X% de contagio.

### ISSUE THREAD

**Issue by fnquinteros** [IIC2115/Syllabus-2018-1#50]
Hola! A pedido de varios de ustedes decidimos mostrar el resultado de una consulta para que puedan comprar resultados, detectar errores y entragarse feedback entre ustedes. Los resultados que se entreguen **pueden no ser correctos** (al fin y al cabo, todos somos humanos), pero el fin de esta issue es poder discutir sobre posibles errores en el modelamiento que puedan llevar a errores en la consulta.

* Está **estrictamente prohibido** mostrar código, ya sea por pantallazo o escribiéndolo. Romper esta regla será considerado copia y será sancionado según la _Política de Integridad Académica_.

Estos son los resultados obtenidos al consultar los primeros países en alcanzar el 60% de contagio:

![image](https://user-images.githubusercontent.com/17592014/31309843-635af086-ab63-11e7-8f34-b039d10db685.png)

**Comment by fnquinteros** [comment]
Como ven, más de un país puede alcanzar el X% de contagio en un día T. Por lo tanto pueden ser los _primeros_ países en vez del _primer_ país.

**Comment by etebrito** [comment]
bacan gracias! Una duda que me quedó...esta es la consulta donde se considera el X% que se contagia "desde" el estado inicial, incluyendo los países focos? o esta es otra? 

Si mal no recuerdo, países foco como Bolivia o Venezuela no están en esta lista porque partieron muy arriba y su "delta" no podría ser 60%, cierto?... si en esta consulta hubieses puesto..no sé..5%...podría aparecer alguno de los países que era focoo?

Gracias y saludos!

**Comment by fnquinteros** [comment]
Exacto, no aparecen los países foco con porcentaje muy alto por lo que dices. Y si, podrían aparecer si se ingresa un X relativamente bajo :)

**Comment by etebrito** [comment]
holaa!! :/

no he logrado ver dónde estoy fallando..pero me es imposible lograr ese nivel de contagio. Las tolerancias de todos los países son bajas, menores que 50% excepto por Argentina y Chile. Los porcentajes iniciales de contagiados de los países "foco" son todos sobre 50%. Por lo tanto, al día 1 se me generan un casi todos los bloqueos hacia los países que contagian.
Esto sucede independiente siquiera de la fórmula de Cp. Después, los países "foco" se infectan más y rápidamente alcanzan un nivel suficiente para que Argentina y Chile los bloqueen...¿Cómo lograste que se contagiaran tantos países? o.O

**Comment by etebrito** [comment]
me di cuenta de que si en cada turno: 
primero actualizo los infectados
después, actualizo los bloqueos

se propaga mucho mejor y hasta se infectan mucho.. eso quiere decir que desde el estado inicial, primero se contagia y después salen los bloqueos..está bien así?

**Comment by etebrito** [comment]
los países subterráneos...pueden sanar a los contagiados? con su cp negativo?

saludos y gracias!

**Comment by fnquinteros** [comment]
Los subterráneos no afectan la infección, ni positiva ni negativamente

**Comment by njara10** [comment]
Puede ser que falte Peru en esa lista? jaja ese tambien me sale. Porfavor avisar

**Comment by jtlafuente** [comment]
No me quedan claros los resultados que publicaste. Esto es para la última consulta del enunciado? Si estás buscando los primeros países en alcanzar el 60% de contagio, por qué aparece "Days passed: 7" ? Hay países con más de 60% de contagio, antes de que hayan pasado 7 días. No será que los resultados son para la primera consulta, "Dado un día T, encontrar los países con porcentaje mayor o igual a X de infectados." ? (con T=7 y X=60)

**Comment by fnquinteros** [comment]
Aparece eso porque trás 7 dias, hay uno o más países que alcanzan el 60% de contagio en comparación al estado inicial. Lo puse solo para poder evaluar que efectivamente en el 7mo día alcanzaban ese porcentaje de infección.

**Comment by fnquinteros** [comment]
Pero son los primeros países en alcanzar ese x% de contagio.

**Comment by jtlafuente** [comment]
Sorry pero entonces todavía no entiendo lo que pide la consulta jaja porque dices que esos son "los primeros países en alcanzar ese x% de contagio". Pero, no necesariamente todos alcanzaron ese x% al mismo tiempo cierto? Entonces la consulta no está pidiendo el PRIMER país en alcanzarlo?

**Comment by fnquinteros** [comment]
el tiempo es discreto, por lo tanto pueden haber pasado de 50% a 70% en un solo T, por lo tanto, puede haber más de un país que alcance el X% al mismo tiempo y no tienes cómo saber cual lo alcanzó primero.

**Comment by jtlafuente** [comment]
Perfecto, entonces viendo los resultados de más arriba, en el día 6 ningún país tenía sobre 60% de infectados? Y al pasar al día 7 los países que aparecen ahí llegaron a tener sobre 60%?

Otra duda que tengo (que quizás ya preguntaron, pero no me quedó clara la respuesta) es por qué para esta consulta no se toman en cuenta a los países que comienzan con un alto porcentaje, por ejemplo Hanslandia que empieza con 91% de infectados. Gracias!

**Comment by fnquinteros** [comment]
Sí se toman en cuenta. Lo que pasa es que para esta consulta, se cuenta la diferencia de contagio entre el estado inicial hasta X%. Por ejemplo, un país A comienza con 30% de infección, al pedir los países que alcanzaron el 60%, podría aparecer A entre los países con un 90% o más, por que desde el estado inicial (30%) se contagió un 60% más. En cambio, un país B que comienza con 70% no puede aparecer en esa misma consulta, pues el máximo contagio que puede alcanzar desde el estado inicial es 30%. Se entiende?

**Comment by fnquinteros** [comment]
@njara10 Perú alcanza un 53% aprox. cuando el resto alcanzó sobre 60%.

**Comment by jtlafuente** [comment]
Muchas gracias @fnquinteros ! entendí todo. Última cosa, mandé una issue (#37) hace varios días pero no ha sido respondida, por si la puedes revisar porfa

**Comment by fnquinteros** [comment]
Lo siento!!! 🙏 Voy conversarlo con los demás y te contesto lo antes posible!
