### ISSUE TITLE
Consulta: Primer país en contagiarse en un X%

### ISSUE THREAD

**Issue by iichandia** [IIC2115/Syllabus-2018-1#51]
Hola,
La consulta dice: "Primer país en que el X% de su población fue infectada."
En un mismo periodo podrían haber alcanzado más de un país a contagiarse en ese  X%, en ese caso se ponen todos los países que consiguieron ese porcentaje?

**Comment by fnquinteros** [comment]
Hola! mira el ejemplo en la issue #50 

Saludos!

**Comment by iichandia** [comment]
Ah buena! sorry, pensé que el ejemplo era de la consulta en que tu le entregabas el día T y te daba los contagiados mayor o igual a X.
Gracias!

**Comment by fnquinteros** [comment]
Es verdad, el título no lo deja claro, voy a cambiarlo
