### ISSUE TITLE
Paises Considerados para poner Cúpula 

### ISSUE THREAD

**Issue by jpzepedanunez** [IIC2115/Syllabus-2018-1#53]
Hola!, una consulta, para calcular el 70% promedio de los paises que me pueden contagiar directamente, ¿se cuentan los paises que ya tienen un campo de fuerza?

**Comment by fnquinteros** [comment]
Hola! Si, se cuentan aunque se hayan rodeado de campos de fuerza por completo.

Saludos!

**Comment by jpzepedanunez** [comment]
Dale, gracias :D
