### ISSUE TITLE
[T03] - Diagrama

### ISSUE THREAD

**Issue by Carlos0C** [IIC2115/Syllabus-2018-1#54]
Tengo una duda sobre el enunciado. En la página 5 dice:

"Recomendamos fuertemente utilizar la siguiente página la cual puede exportar el diagrama en PDF y agregarlo al latex" ... ¿a cuál página hacen referencia?

Muchas gracias de antemano

**Comment by Hernan4444** [comment]
@Carlos0C la palabra `página` está vinculada a la pagina, es un hipervinculo jejeje. De todos modos te lo indico, es https://www.draw.io

Saludos ✌️

**Comment by diflores** [comment]
Hola,

La palabra página contiene un hipervínculo a dicho sitio, que corresponde a [este](https://www.draw.io).

¡Saludos!

**Comment by Carlos0C** [comment]
jajaja gracias !!
