### ISSUE TITLE
T03 - Evaluación Usuario - Película 

### ISSUE THREAD

**Issue by ndschnitzler** [IIC2115/Syllabus-2018-1#55]
Hola! 

Una consulta, un usuario puede evaluar una película mas de una vez? Y en caso de que no pueda, se considera una película como aquellas con titulo distinto, o aquellas con titulo y genero distinto?

Gracias!

**Comment by VinceValence** [comment]
Hola

Sí, un usuario puede evaluar una película más de una vez, pero es importante que sólo la última evaluación sea la que se vea reflejada en la base de datos.
En la tarea, debes identificar cada película dependiendo de su título. Esto quiere decir que una película tiene el mismo título que otra si y solo si son la misma película. 
Una consecuencia de lo anterior (dada la naturaleza de los datos) es que una misma película puede tener más de un género.

**Comment by etebrito** [comment]
Hola! Respecto a esto mismo, el hecho de que una película pueda tener más de un género...un rating hecho por un usuario a una película particular, en un instante particular, aparece repetido en el .csv con distintos géneros para esa película. La película se reconoce entonces como que cualquiera de esos géneros sirve para caracterizar esa película..pero el rating realizado en ese día y hora particular, cuenta como UN rating (aunque aparezcan 3 filas en el .csv), cierto? nosotros vemos como armar bien las tablas, pero en el .csv..es como si alguien hubiese rateado la película y se hubiese almacenado una fila para cada género? 

pregunto pensando en las consultas 3, 4 y 5 donde la cantidad es importante.

Gracias de antemano!

**Comment by Hernan4444** [comment]
@etebrito precisamente en el csv, cuando alguien ratea una pelicula, ese rating se copia para cada género de la película, pero sabemos que eso está mal puesto que estamos duplicando mucho información. La idea es que sus nuevas tablas solucionen ese problema y al momento de ratear, solo se agrege una fila a alguna tabla de ustedes.

Saludos ✌️
