### ISSUE TITLE
[T03] Sobre un par de consultas, y el informe

### ISSUE THREAD

**Issue by idmdvan** [IIC2115/Syllabus-2018-1#56]
Hola! Quisiera saber si pueden aclarar más un poco lo que deben realizar las siguientes consultas:
> 4. Dada una ocupación, entregar el género más rateado por personas con esa ocupación.

Esta consulta debe retornar el género con mejor calificación, o con mayor número de calificaciones? 
Y,
> 5. Dadas dos fechas, mostrar la película (que no haya sido estrenada entre las fechas) más rateada por mujeres entre las fechas con ratings sobre el promedio de ratings de mujeres entre las fechas y la película que cumpla las mismas condiciones, pero para hombres.

De nuevo, "más rateada" significa con mejor calificación o con mayor número de calificaciones? Lo entiendo como que debe mostrar la película mejor calificada por las mujeres entre un par de fechas, pero no entiendo lo del "promedio de ratings de mujeres entre las fechas". 

Eso, muchas gracias! =)

**Comment by idmdvan** [comment]
También entiendo por el enunciado que esta vez solo hay que entregar el diagrama, y no hay que hacer informe en LaTeX. Es así ? Gracias!

**Comment by diflores** [comment]
Hola, 
Responderé por partes:

1. Más *rateado* significa con mayor cantidad de ratings.
2. Cito: 

> «Además, deberás explicitar y explicar la secuencia de pasos que gatilla cada una de tus consultas en tu base de datos, incluyendo la generación de tablas intermedias o parciales por medio de joins o selecciones. Es muy importante que tus explicaciones sean lo mas detalladas, claras, precisas y concisas posible. Por ejemplo, un paso en una consulta podra ser: "selección de todas las las que tengan cierto atributo mayor a 8. Este paso genera un grupo de las que puede ser mas pequeño que la tabla sobre la cual se ejecuta la
seleccion."»

EDIT: olvidé responder sobre la consulta 5, en relación a ella: «promedio de ratings de mujeres entre las fechas» significa que de todos los ratings emitidos por mujeres, te interesa solo el promedio de los que fueron enviados en el intervalo de tiempo que se entrega a la consulta.

**Comment by idmdvan** [comment]
Gracias ! :)
