### ISSUE TITLE
Error que no entiendo

### ISSUE THREAD

**Issue by sgmigliaro** [IIC2115/Syllabus-2018-1#58]
Hola, al intentar pasar los datos a mis tablas me esta dando un error donde no pasa nada, es decir si paro el Kernel de Jupyter me sale:
```python
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-18-338bada89de9> in <module>()
     13     if b == []:
     14         c.execute("INSERT INTO usuarios VALUES (?) ", datos_usuarios)
---> 15     d = c.execute("SELECT * FROM peliculas P WHERE P.movie_title = ?", (s[5],))
     16     if d == []:
     17         c.execute("INSERT INTO peliculas VALUES (?, ?, ?)", datos_peliculas)

KeyboardInterrupt: 

```
Como ven esta vacia la razon del error. Se que no se podia poner codigo pero como esto es un error y aparece poco codigo supongo que esta bien? Gracias!

**Comment by Hernan4444** [comment]
@sgmigliaro puede ser que estás guardando lo que retorna `c.execute` en una variable cuando eso no se debe hacer. Solo sirve para itelar sobre él (revisa la mini solución subida) o utiliza `fetchall` si es que quieres la lista.

Cuantame como te va con esos cambios.

**Comment by sgmigliaro** [comment]
Si, creo que es eso, me acabo de dar cuenta, gracias!
