### ISSUE TITLE
Ocupación Administrator y Consulta 4

### ISSUE THREAD

**Issue by padelabarra** [IIC2115/Syllabus-2018-1#59]
Algunas personas del .CSV tienen como ocupación Administrator, esto quiere decir que son usuarios administradores o que se dedican a ser administradores en su vida daria (actualmente lo estoy considerando como lo segundo). 

Y otra duda, en la Consulta 4 donde se debe retornar el genero más rateado, esto significa el genero al que le han hecho más rating en términos de cantidad cierto? No el con una nota promedio mayor.

**Comment by diflores** [comment]
Significa que desempeñan labores administrativas en su vida diaria, así que está bien lo que haces :)
Sobre lo segundo, ya respondí algo parecido en otra *issue*: el «más» hace referencia a **cantidad** de *ratings*.

¡Saludos y éxito con la tarea!
