### ISSUE TITLE
return self

### ISSUE THREAD

**Issue by marcelodutilh** [IIC2115/Syllabus-2018-1#6]
No entiendo porque en todos o casi todos los Tree Traversal se usa <self.ret> y <return self>..
lo que mas o menos logro entender es que uno crea un self.ret para que cada nodo lo retorne y cuando  uno va dentro de la recursion se van imprimiendo esos self.ret por que es lo que retorna cada print de cada nodo... puede que este equivocadisimo.. y por otro lado el return self no tengo idea de porque esta.. 
Muchas gracias.

**Comment by Hernan4444** [comment]
La idea que tienes está bien.

El `self.ret` al final es un atributo que  todos los nodos ván a compartir el cual le irán agregando información de forma recursiva y así tener al final un string con toda la información de los nodos.

Si la explicación no te despeja las dudas vuelva a preguntar e intentamos explicar desde otro punto 😃.

Saludos!!

Ps: el `return` está de más en esta ocasion.
