### ISSUE TITLE
Tarea 3

### ISSUE THREAD

**Issue by mjgomez3** [IIC2115/Syllabus-2018-1#60]
como creo una tabla películas que no tenga nombres de películas repetidos?

**Comment by Hernan4444** [comment]
@mjgomez3 no olvides las reglas de foro. (#2).
> Busca en el material del curso.
Si sigues sin entender o sin resolver tu duda, busca en Internet para encontrar la solución. Google será tu mejor amigo este semestre
Si el problema persiste o sigues sin entender, entra a Issues.

Crear elementos únicos es algo que se especifica en el material y tambien es un problema que se ha resuelto en internet en todos los lenguajes que existe y de diferentes formas, debes encontrar una que se ajuste a tu forma de modelar.

Saludos ✌️

**Comment by Hernan4444** [comment]
@mjgomez3 algunos hint:
- Pasar los datos por un `set` (estructura de datos de python)
- Investigar `Distinct` y/o `Llave Primaria`

Saludos ✌️
