### ISSUE TITLE
Error repetido

### ISSUE THREAD

**Issue by sebalinderman** [IIC2115/Syllabus-2018-1#61]
Hola, varias veces me ha entregado este error y no se qué significa. 

<img width="801" alt="captura de pantalla 2017-10-25 a la s 13 45 30" src="https://user-images.githubusercontent.com/30681880/32011376-f97aaf54-b98a-11e7-855f-85da214ccc9b.png">

Si hago ese mismo SELECT, pero fuera del "for", me entrega lo que le pido. De hecho, antes de esto hago otro "for" y me entrega el valor bien. Gracias!

**Comment by Hernan4444** [comment]
@sebalinderman puedes agregar un `print` entre la línea 24 y 25, puede ser que `pe` toma un valor indeseado.

Cuentame como te va.

Saludos ✌️

**Comment by sebalinderman** [comment]
Imprime el nombre de la película, nada indeseado:

<img width="505" alt="captura de pantalla 2017-10-25 a la s 14 40 45" src="https://user-images.githubusercontent.com/30681880/32013792-872cb534-b992-11e7-928a-31bebcf720fd.png">

**Comment by sgmigliaro** [comment]
A mi tambien me esta molestando con algo parecido: 

```python
    133             borrar = input('Ingrese nombre de usuario a borrar: ')
    134             c.execute("DELETE FROM usuarios WHERE user_name = ?", (borrar, ))
--> 135             c.execute("DELETE rating FROM rating INNER JOIN usuarios ON rating.user_id = usuarios.user_id WHERE user_id = ?", (borrar, ))
    136             connection.commit()
    137 

OperationalError: near "rating": syntax error
```

**Comment by pedrosantelices** [comment]
el near "s error es por peíiculas por ejemplo what's eating ...  que tienen apostrofe s, en géneros también pasa con el genero childen's

**Comment by sebalinderman** [comment]
Toda la razón, cuando trato de hacer:

<img width="781" alt="captura de pantalla 2017-10-25 a la s 17 48 53" src="https://user-images.githubusercontent.com/30681880/32022448-ceb9265c-b9ac-11e7-9d50-03592c951ea2.png">

El problema lo tiene con la película pe = "It's a Wonderful Life (1946)". Alguna idea de cómo arreglarlo?

**Comment by Hernan4444** [comment]
Una idea es usar `replace` y cambiar los `'` por `"` y ver como les funciona 👀 

Saludos ✌️

**Comment by pedrosantelices** [comment]
yo hice replace ' por nada y me funcionaba, por ejemplo quedaba its

**Comment by sebalinderman** [comment]
Solucionado, gracias!

**Comment by sgmigliaro** [comment]
Estoy con este problema utilizando la funcion DELETE, alguien sabe que puede pasar? trate de muchas formas y no lo estoy logrando. Gracias!

```python
<ipython-input-9-d13d29e62829> in Admin(user_id)
    135             c.execute("DELETE FROM usuarios WHERE user_name = ?", (borrar, ))
    136             c.execute("DELETE rating FROM rating INNER JOIN usuarios ON rating.user_id = usuarios.user_id WHERE "
--> 137                      "usuarios.user_name = ?", (borrar,))
    138             #c.execute("DELETE FROM rating WHERE usuarios.user_name = ? AND usuarios.user_id = rating.user_id", (borrar, ))
    139             connection.commit()

OperationalError: near "rating": syntax error
```

Probe sacando el rating entremedio del DELETE y el FROM pero sigue molestando.
Tambien probe sacnado el INNER JOIN como aparece comentado (#) despues del error, y me tira otro error. E

**Comment by Hernan4444** [comment]
@sgmigliaro puedes subir tu tarea lo más actualizada posible para ver el error.

Saludos ✌️

**Comment by sgmigliaro** [comment]
@Hernan4444 Listo, la acabo de subir

**Comment by Hernan4444** [comment]
@sgmigliaro lo que estaba leyendo (y probando con tu tarea) es que SQLite3 no soporta DELETE con JOIN juntos. Lo que deberías hacer en ese caso es obtener el ID que buscas (con una consulta) y luego hacer otra donde eliminas los rating con ese ID.

Saludos ✌️

**Comment by sgmigliaro** [comment]
@Hernan4444 aah ya me imagine que podria ser por esa razon. Gracias!
