### ISSUE TITLE
Formato fechas

### ISSUE THREAD

**Issue by sebalinderman** [IIC2115/Syllabus-2018-1#62]
En el enunciado dice que las fechas tienen formato "YYYY-MM-DD", pero viendo el excel veo que están escritas como "DD-MM-YYYY". Por ejemplo, si quiero crear una película, con cuál de los 2 formatos me quedo? Hasta ahora estoy siendo consistente con lo que sale en el excel. Gracias!

**Comment by Hernan4444** [comment]
@sebalinderman para comprobar el formato de las fechas te sugiero que hagas:
```python
archivo = open("....csv")
for line in archivo:
    print(line)
```
Excel tiende a cambiar el formato de los csv a uno que él maneje. Si estás siendo consistente con excel, es muy probable que se caiga despues.

Saludos ✌️ 

edit: Si imprimes los datos y tienen el formato que excel indica, entonces avisanos para cambiar eso del enunciado.

**Comment by sebalinderman** [comment]
Acabo de imprimir la fecha por ejemplo para la película "Young Frankenstein (1974)" y me imprime la fecha así "01-01-74".

**Comment by Hernan4444** [comment]
@sebalinderman puede ser que estás trabajando con una base de datos ya editada por 2 motivos:
1. Los años aparecen con 4 números y en tu caso hay solo 2
2. Acabo de hacer print con la base de datos del Syllabus y me aparecen así
> 399;25;"M";"Other";92374;"Scream (1996)";"1996-12-20";3;"Thriller";"1997-12-16 22:30:00"
399;25;"M";"Other";92374;"Lord of Illusions (1995)";"1995-01-01";1;"Horror";"1997-12-17 00:57:02"
399;25;"M";"Other";92374;"Jerry Maguire (1996)";"1996-12-13";3;"Drama";"1997-12-18 21:48:10"
399;25;"M";"Other";92374;"Jerry Maguire (1996)";"1996-12-13";3;"Romance";"1997-12-18 21:48:10"
399;25;"M";"Other";92374;"Down Periscope (1996)";"1996-03-01";2;"Comedy";"1997-12-17 00:54:10"
399;25;"M";"Other";92374;"It's My Party (1995)";"1996-03-22";3;"Drama";"1997-12-16 22:40:27"

Y viendolos desde el navegador, tambien tienen el mismo formato:
![image](https://user-images.githubusercontent.com/15641721/32028065-f4fe2bee-b9c2-11e7-898c-cebbfd96dcd8.png)

Prueba descargando de nuevo la base de datos. Puede ser que como empezas con ese supuesto, sobreescribiste los datos originales con los nuevos.

Saludos ✌️

**Comment by sebalinderman** [comment]
Sí, en el navegador también me salen así. Pero me descargo el archivo .csv y las fechas se me ven así:

<img width="84" alt="captura de pantalla 2017-10-25 a la s 20 40 21" src="https://user-images.githubusercontent.com/30681880/32028389-ca8dfc98-b9c4-11e7-8c0a-5500cc44ced8.png">

Pero al seleccionarla me sale así:

<img width="211" alt="captura de pantalla 2017-10-25 a la s 20 40 35" src="https://user-images.githubusercontent.com/30681880/32028398-d2850540-b9c4-11e7-969d-f936f9160f95.png">

**Comment by hanavarrete** [comment]
Lo que pasa es que en excel se seguirá viendo diferente siempre. **No** uses excel para basarte en eso. Saludos!

**Comment by sebalinderman** [comment]
Sí, lo tengo claro, pero si hago lo siguiente:

<img width="825" alt="captura de pantalla 2017-10-25 a la s 20 55 24" src="https://user-images.githubusercontent.com/30681880/32028863-0dd9e712-b9c7-11e7-999a-353c6e174422.png">

Me sigue tirando la fecha de la misma forma. Es mucho problema si considero este formato en el código?

**Comment by fnquinteros** [comment]
Puedes hacer commit de tu código para ver algo, por favor?

**Comment by sebalinderman** [comment]
Dale ahí lo hice

**Comment by fnquinteros** [comment]
para descargar el archivo estás haciendo pull o descargando lo directo del syllabus? Estas abriendo el archivo a mano una vez que lo descargas? Podrías probar hacer pull del syllabus de nuevo y abrir el archivo desde python sin haber abierto antes a mano el csv, por favor?

**Comment by sebalinderman** [comment]
Buena ahí sí, si no abro el archivo queda en el formato correcto. Gracias!
