### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mandrade1** [IIC2115/Syllabus-2018-1#63]
hola me tira este error y no tengo idea porque. Si saco el codigo drop me dice que la tabla ya ha sido creado y si lo dejo me tira lo siguiente

`OperationalError                          Traceback (most recent call last)
<ipython-input-37-f9647bb1db05> in <module>()
      1 connection = sqlite3.connect("T03.db")
      2 cursor = connection.cursor()
----> 3 cursor.execute("DROP TABLE Usuario")
      4 cursor.execute("DROP TABLE Pelicula")
      5 cursor.execute("DROP TABLE Rating")

OperationalError: database is locked`

**Comment by Hernan4444** [comment]
@mandrade1 estuve leyendo sobre este error y se da cuando se hizo una acción con la base de datos y ya se está haciendo otra cuando todavía no termina la primera. Puede ser que tu T03.db tiene algo que se demora en procesar y cuando haces `cursor.execute("DROP TABLE Usuario")`. Podrías intentar hacer:
```python
connection = sqlite3.connect("T03.db")
cursor = connection.cursor()
```
En una casilla del jupyter y en otra casilla hacer los `DROP`, así le das un poco de tiempo a la base de datos de terminar su proceso antes de comenzar otro. En caso de no funcionar avisame para descartar esto como una posible razón.

Saludos ✌️
