### ISSUE TITLE
Admins

### ISSUE THREAD

**Issue by ndschnitzler** [IIC2115/Syllabus-2018-1#64]
Hola! 
¿La idea es que al momento de registrarse uno puede elegir si es admin o no? ¿O los admin son asignados de alguna otra manera?
Gracias!

**Comment by Hernan4444** [comment]
@ndschnitzler tienes que asignar algunos usuarios como administradores de forma manual y en el informe o en el `.ipynb` indicar cuales usuarios son y sus contraseñas.

Saludos ✌️

**Comment by rtrucco** [comment]
Entonces, ¿user_occupation no te dice cuales son administradores? Por que hay una ocupación que se llama Administrator.. O eso se refiere a que ese usuario tiene como profesión administrar algo y no es que el sea un usuario de categoría administrador.

Gracias!

**Comment by Hernan4444** [comment]
precisament 👍

**Comment by Tamarainfante** [comment]
Hola, @Hernan4444 no me queda claro. 
Es decir, nosotros solos libre de darle a algunos usuarios la oportunidad de ser administradores al crearse o no? 
Podrías ser más claro al ejemplificar esto, gracias!

**Comment by Hernan4444** [comment]
@Tamarainfante es tal como indicas. Tu tienes la libertad de poner usuarios como administradores. Las opciones son:
1) Durante el registro de un usuario en la consola, le preguntas si quiere ser admin o no (Esto no sigue la lógica, pero filo)
2) Que tu escojas una cantidad arbitraria de usuarios y los dejas como admin. Luego en el informe o en el mismo código nos dices: El usuario "Pepito" es admin y su password es "123asdSa".

Ahí si se entiende?

**Comment by Tamarainfante** [comment]
@Hernan4444 Perfecto, me queda mucho más claro. 

Gracias por la rapidez al responder :D
