### ISSUE TITLE
Simulación DES Ejercicio propuesto

### ISSUE THREAD

**Issue by Hernan4444** [IIC2115/Syllabus-2018-1#65]
Estimados, 
  Primero queremos  aclarar que la dificultad de la actividad del jueves pasado es solo una cota inferior a la dificultad de la actividad de la próxima semana. 

  En vista que esta clase no tuvieron mucho tiempo para practicar con simulación, aquí les presentamos la AC01 de Programación Avanzada sobre Simulación DES. Tomen esta actividad como una aproximación a la dificultad de su AC02 de Simulación. 

[Enunciado.pdf](https://github.com/IIC2115/Syllabus/files/1422296/Enunciado.pdf)

Cualquier duda, no olviden consultar en las Issues.
Saludos ✌️

**Comment by jtlafuente** [comment]
Hola, tengo una duda del enunciado. Al principio dice que la base "Segurita" está a 50km de Calle Larga. También dice que la posición inicial de las personas es aleatoria entre 0 y 60km. No entiendo la "geografía" del problema, la posición inicial de las personas se mide entre Calle Larga y "Segurita"? Si la distancia total es 50km, cómo puede una persona comenzar a 60km? 
De ser así, si una persona comienza a 50km de Calle Larga significa que ya se encuentran en la base?
Saludos!

**Comment by Hernan4444** [comment]
@jtlafuente el enunciado tiene un error, si revisas las **Notas** dice:
> La base se encuentra en el kilómetro 100,

Ese es el dato final que necesitas considerar. Por lo tanto, nadie empieza en la base "Segurita".

Saludos ✌️
