### ISSUE TITLE
Preguntas Varias Tarea3

### ISSUE THREAD

**Issue by patocourta** [IIC2115/Syllabus-2018-1#66]
Tengo varias consultas, algunas son cortas asi que prefiero preguntarlas juntas, para no crear muchas issues.

1- Puedo asumir que el user_id en el archivo.csv siempre se mostraran de forma creciente +1? O van a probar con archivos que por ejemplo muestren los rating del usuario id=1 y luego usuario id=100.
2- Los nombres de las peliculas son unicos? O debo formar la unicidad con algun otro valor.
3- Puedo cortar las fechas (minuto y segundo) del rating_date?. Ninguna consulta solicita los minutos y de esa forma de trabaja mas facil ese campo.
4- Hay mas generos que los expuestos en el archivo? Hice la tarea de forma que busca todos los generos en el archivo, y solo le muestro esas posibles opciones al admin al momento de crear una pelicula nueva.
5- Parecido al punto (4), cuando alguien crea un nuevo usuario, puede poner una ocupacion no existente en el archivo?
6- Todos los usuarios en el archivo son normales? Lo hice de esa forma, y que para agregar peliculas hay que explicitamente crear un admin despues en el menu.
7- Todos los user_name y password que debemos generar seran simbolicas? Osea, hay unos 900 usuarios en la bd, asi que supongo que hay que crear una funcion random que cree las pass que quedarian guardadas en la bd pero no las "conoceriamos" como usuarios externos, asi que ningun usuario del archivo podria entrar al sistema a traves del menu, solo los usuarios que creemos despues a los que le conozcamos el user_name y las password podran entrar.
8- Como debe el funcionamiento general del programa?. Me refiero por ejemplo, cuando ejecuto el programa crea todas las tablas, me guarda los datos del archivo y creo nuevos usuarios. Cuando lo ejecute de nuevo, ya comienzo con la base de datos anterior, o se debe hacer todo de 0?

**Comment by Hernan4444** [comment]
Hola!!
1. No puedes asumir eso. Algunos usuarios de nuestra base de datos podrían ya haber sido baneados y por ello tendrás id faltantes y si el programa reasigna el id, puede ser que el id faltante esté al final. Lo mejor es siempre leer la información tal como viene del archivo, sin hacer supuestos sobre orden.
2. Esto ya se respondió #55 
3. Si puedes
4. No hay más géneros.
5. Eso no quedó bien especificado en el enunciado así que queda a tu criterio. Si quieres puedes solo poner la respuesta que entrega el usuario o darle una lista de opciones.
6. Eso queda a criterio tuyo, si quieres puedes hacerlos normales o dejar algunos como admin, como quieras.
7. Si, serían simbólicos, pero lo ideal sería que guardarás al menos una contraseña de un usuario para poder ingresar con él y ver si todo funciona bien con alguien que no fue "registrado" a la base de datos, sino que ya estaba en ella. Sino, nosotros haremos `Select * from Usuarios` (suponiendo que Usuarios es la tabla con toda esa información) y veremos alguna password.
8. Como Jupyter Notebook tiene diferentes casillas para ejecutar, podrías dejar una para preprocesar los datos, es decir, leer el .csv y crear el .db. Así nosotros ejecutamos esa casilla solo una vez y después solo ejecutamos las demás casillas para poder interactuar con tu programa.

Ojalá haya resuelto todas tus dudas. Éxito en la tarea!!
Saludos ✌️
