### ISSUE TITLE
Problema tiempo ejecución consultas

### ISSUE THREAD

**Issue by MaximoVillarinoSelman** [IIC2115/Syllabus-2018-1#67]
Hola!

Cuando hago consultas por SQL que involucran sólo una tabla de las creadas,  el programa entrega la respuesta inmediatamente.
Ej: SELECT * FROM usuarios

Pero cuando hago consultas que incluyen dos tablas el programa no deja de ejecutarse y no entrega nada. (Incluso se me ha quedado pegado el computador varias veces y lo tengo que reiniciar).
Ej: SELECT nombre FROM usuarios, ratings WHERE puntos = 4

No se si es un problema con mi modelación o si a todos les pasa.
Entonces la idea es que respondamos a las consultas sólo consultado una tabla a la vez?

Gracias.

**Comment by Hernan4444** [comment]
@MaximoVillarinoSelman debe haber un error en la modelación, puesto que implenté eso mismo que tu pusiste y no pasa nada. La idea no es que hagan la consulta a una tabla a la vez, sino que aprovechen de los `JOIN`, `WHERE`,  ~`GROUP BY` para no realizar todo con python.

Talvez puede ser que la tabla `ratings` tiene algún error? Te funciona cuando haces select * from ratings?

**Comment by MaximoVillarinoSelman** [comment]
Buena Hernán gracias por la ayuda.

Cacha que haciendo select * from ratings también se pega.
Lo encuentro raro porque las otras dos tablas me funcionan bien y las hice de la misma forma

**Comment by Hernan4444** [comment]
@MaximoVillarinoSelman puedes subir tu tarea?, talvez hay un ligero detalle que se está pasando.

**Comment by MaximoVillarinoSelman** [comment]
Acá te adjunto unos pantallazos.
Esta es la función que "pobla" mi tabla de ratings:
![image](https://user-images.githubusercontent.com/30697801/32146833-4ac92712-bcbc-11e7-9957-74432bc00b09.png)

Cuando le hago print a lo que va dentro del format se imprime esto:
![image](https://user-images.githubusercontent.com/30697801/32146871-9b216670-bcbc-11e7-8b5f-4101499a85a1.png)

Y cuando hago la consulta que me dices me pasa esto:
![image](https://user-images.githubusercontent.com/30697801/32146884-bf4e6a7a-bcbc-11e7-8d34-db5ef5ab410c.png)

Quedo atento al problema, muchas gracias

**Comment by Hernan4444** [comment]
@MaximoVillarinoSelman necesito que subas tu tarea please xD Necesito jugar un poco con el código para ver mejor el error.

**Comment by MaximoVillarinoSelman** [comment]
[Tarea+3.zip](https://github.com/IIC2115/Syllabus/files/1425391/Tarea.3.zip)

Acá está dentro de un zip

**Comment by Hernan4444** [comment]
@MaximoVillarinoSelman con "subir tu tarea" era que hicieras push a tu repositorio privado. Ahora tu tarea quedó pública para todos. Solo quiero recordar que cualquier caso de copia, será sanciado fuertemente.

ps: Ahora veré tu tarea.
Saludos ✌️

**Comment by MaximoVillarinoSelman** [comment]
Perdona Hernán no sabía que querías que la subiera ahí y que ahí la podías ver, no fue con ninguna mala intención. 
Avísame si cachas que onda porfa!
gracias

**Comment by Hernan4444** [comment]
@MaximoVillarinoSelman el error es que cuando pones `print` del resultado, estás pidiendo que junte todo el resultado en forma de un string gigante y ahí imprimirlo. Juntar todo eso es imposible, pero si haces:
```python
cursor.execute("SELECT * from ratings")
cursor.fetchall()
```
En una sola casilla, harás que jupyter notebook muestre los resultados de a poco y no tenga que juntar todo de golpe.  La otra opcion es hacer:
```python
cursor.execute("SELECT * from ratings")
for elem in cursor.fetchall():
    print(elem)
```

En base a lo anterior, cuando hagas consultas con dos tablas, tienes que hacer lo mismo que dije antes. (un for para print)

**Comment by MaximoVillarinoSelman** [comment]
Buena Hernán muchas gracias.

Ahí puedo acceder a la consulta.

Te pasaste
