### ISSUE TITLE
Duda inner join

### ISSUE THREAD

**Issue by sgmigliaro** [IIC2115/Syllabus-2018-1#68]
Hola, no entiendo cual es la diferencia entre hacer un WHERE A.name = B.name y un inner join. Por ejemplo,
1) SELECT T.departamento FROM persona P, trabajo T WHERE P.name = T.name
2) SELECT T.departamento FROM trabajo T INNER JOIN persona P ON P.name = T.name

Si no me equivoco los dos hacen lo mismo? o en que caso seria mas util usar inner joins? gracias!

**Comment by Hernan4444** [comment]
@sgmigliaro no estás equivocado. Ambas consultas exactamente lo mismo.  Según lo que leí en internet, el `INNER JOIN` fue creado en 1990, puede ser (es una suposición lo que leí) que en esos tiempos el `WHERE `e `INNER JOIN` no estaban optimizados como debían y ahí uno era preferible que el otro. Pero ahora muchas páginas coinciden que su implementación es igual y por lo tanto no hay mucho que decir.  
En base a esto, no conozco un caso donde sería más util usar INNER JOIN.

Saludos ✌️
