### ISSUE TITLE
Problema de ejecución

### ISSUE THREAD

**Issue by saboetto** [IIC2115/Syllabus-2018-1#69]
Hola! tengo un problema con la parte en donde agrego los datos a mi tabla de Ratings, ya que el programa se pone a correr y en el Input me sale "In [*]" durante mucho rato, como si estuviera procesando. Como arreglo este problema? ya que necesito la tabla para poder avanzar con las consultas. Gracias!

**Comment by Hernan4444** [comment]
@saboetto puedes ser que la forma que agregas los datos es super lenta, primero sugiero agregar un print dentro de lo que estés haciendo para verificar si está haciendo lo que piden (o entró en un loop infinito). Despues, si quieres detener eso, debes ir a `kernel` y poner `interrumpir`. Así, al menos, puedes detener lo que estaba haciendo, cambiar algo y seguir viendo que pasa.

**Comment by saboetto** [comment]
Es que no sé si es lento lo que hago, porque para mi tabla de "géneros de película" hago exactamente el mismo código con un par de variables cambiadas, pero no se me pega. Qué hago?? No puedo avanzar si no se hace la tabla :(

**Comment by Hernan4444** [comment]
@saboetto que puede ser que generos sea mucho menos lo que hay que hacer en comparación a los rating. de todos modos, sube tu tarea (a tu repo) para echarle una mirada.

**Comment by saboetto** [comment]
Ahí lo subí. Porfa avísame si encuentras algo, por favor. Gracias!!!

**Comment by Hernan4444** [comment]
@saboetto lo que pasa es que estás haciendo ` if tuplax not in mov_us_unicos` lo cual hace que para cada fila de la base de datos, tiene que verificar si no está en esa lista. 

La base de datos tiene 212.585 filas, eso implica que cuando ya estés en la mitad (100.000), para cada fila que intentes agregar, necesitas comparar con 100.000 datos más para verificar que no esté.

Por otro lado, en las otras casillas, como hay elementos más repetidos, ` if tuplax not in mov_us_unicos` tiende a tirar `False` antes, pero en los raiting, los datos son muuuucho menos repetidos y por lo tanto, ese condicional tiene que pasar por cada dato de la lista para poder decir `True` (mucho procesamiento)

Finalmente, estás comparando string, para comparar string, el computador tiene que comparar letra por letra. Lo cual, si suponemos que cada película son de 10 letras, cuando estés agregando el dato de la mitad del .csv, el computador tiene que procesar 1.000.000 de comparaciones para continuar. 

Como hint: comparar números (o `id`) es muucho más rápido que comparar string.

Saludos ✌️

**Comment by saboetto** [comment]
buenísima! muchas gracias! 
PD: al final igual me corre el código, pero se demora un ratito
