### ISSUE TITLE
Sobre el ejemplo de matrices de incidencia

### ISSUE THREAD

**Issue by idmdvan** [IIC2115/Syllabus-2018-1#7]
Hola, 

Estaba leyendo la explicación de formas de representar un grafo (matrices de incidencia), y no entiendo algo, si en el ejemplo están representando este grafo: 

![image](https://user-images.githubusercontent.com/30812134/29895075-1cfdcffa-8dae-11e7-8aa0-5c01cbceb5f0.png)

Con esta matriz: 

`
[1, 0, 0, 0, 0, 1]
[1, 1, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 0]
[0, 0, 1, 0, 1, 0]
[0, 0, 0, 1, 1, 1]`

Cómo es que hay seis columnas, si solo hay cinco aristas, o relaciones? Quizás se trata de otro ejemplo? 

De igual manera con el grafo dirigido.

Gracias!

**Comment by halobel** [comment]
Toda la razón, faltó especificar que para la matriz de incidencia, los ejemplos no corresponden a los grafos que aparecen al principio. 
Gracias por el comentario!
