### ISSUE TITLE
Duda con el año en el titulo de las peliculas

### ISSUE THREAD

**Issue by patocourta** [IIC2115/Syllabus-2018-1#70]
Cuando vemos los titulos de las peliculas, se puede ver que todas tienen el año de estreno entre parentesis.
Cuando el usuario quiera buscar peliculas o cuando un administrador agregue peliculas debe añadirles el año tambien? O es correcto, al momento de crear la BD eliminar esa parte del titulo y despues realizar todo tipo de consultas sin el año incluido.

Y otra duda aparte, esta bien que el llenado de la BD se tarde 10 segundos aprox, o debe ser mas rapido?

Gracias.

**Comment by Hernan4444** [comment]
@patocourta como eso no se especificó bien en el enunciado, queda a tu criterio cómo lo abordas. Solo recuerda especificarlo en el informe en el código si es necesario poner fechas o no.

Sobre tu duda aparte, creemos que se puede más rápido, pero 10 segundos es igual un tiempo razonable, así que no te preocupes c:

Saludos ✌️
