### ISSUE TITLE
Template T3

### ISSUE THREAD

**Issue by macatalantalan** [IIC2115/Syllabus-2018-1#73]
Hola! 

Hay un template subido para la portada, no es editable, no recuerdo cuál ayudante había sido, pero sería genial si pueden subirlo (con el título T3)
Gracias

Saludos!

**Comment by jpzepedanunez** [comment]
En el que subieron, anda a los archivos. El que tiene nombre MD_estilo.sty, abrelo y busca donde salga la tarea, lo cambias a T03 y listo.
