### ISSUE TITLE
No tengo feedback

### ISSUE THREAD

**Issue by mjgomez3** [IIC2115/Syllabus-2018-1#74]
Hola, no encuentro en mi repositorio mi feedback de la tarea 2. Qué puede ser?

**Comment by Hernan4444** [comment]
@mjgomez3 hubo un ligero error y tu feedback no se subió como correspondía. Acabo de subirlo de forma manual a tu repositorio.

**Si alguien más no tiene feedback, que avise por este medio por favor.**

Saludos ✌️

**Comment by njara10** [comment]
Yo tampoco tengo feedback.

Saludos

**Comment by Hernan4444** [comment]
@njara10 acabo de subir tu feedback 👍 

Saludos ✌️

**Comment by njara10** [comment]
Gracias!
