### ISSUE TITLE
capacidad scooters

### ISSUE THREAD

**Issue by baltagonzalez** [IIC2115/Syllabus-2018-1#77]
Cuál es la capacidad de cada marca de los scooters?
No aparece en el enunciado.

**Comment by Hernan4444** [comment]
@baltagonzalez tienes que poner, al inicio de la tarea, 2 variables que definan la capacidad de cada tipo de _scooters_ y poner los número que tu quieras. Ej:
```python
CAPACIDAD_DEFECTUOSO = 10
CAPACIDAD_LOBEL = 5
```

Así nosotros podemos cambiarlos cuando queramos.
Saludos ✌️

**Comment by baltagonzalez** [comment]
Gracias!
