### ISSUE TITLE
aterrizaje drones

### ISSUE THREAD

**Issue by baltagonzalez** [IIC2115/Syllabus-2018-1#78]
cuando envió un drone, como sé donde va a aterrizar?
la posición del aterrizaje será un randint(0,1000)?

**Comment by Hernan4444** [comment]
@baltagonzalez recuerda que los drones no llegan al acantilado (que es la posición 1000), así que el randint sería entre 0 y 999.

Saludos ✌️

**Comment by fomorales** [comment]
Y todos los drones parten en el inicio con Bastián? o están repartidos aleatoriamente?

**Comment by Hernan4444** [comment]
@fomorales esa información es irrelevante para esta tarea. Que partan con Bastián o de un lado aleatorio no influye

Saludos ✌️
