### ISSUE TITLE
[T01] Duda sobre los transbordos

### ISSUE THREAD

**Issue by fomorales** [IIC2115/Syllabus-2018-1#8]
En cada uno de los modelos nos entregan las conexiones que tiene cada una de las estaciones, con eso podemos saber si las estaciones pertenecen a la misma línea, sin embargo, creo que no se puede saber con exactitud si se debe hacer un cambio de línea en dichas estaciones.  

Por ejemplo, si quiero en el modelo 1 irme desde U. de Santiago a Las Rejas, debo pasar por la estación Pajaritos, y ahí no sé si quedarme en la misma línea o tener que transbordar hacia otra línea, ya que la estación Pajaritos tiene 4 conexiones en ese modelo, entonces no sé si contarlo como transbordo o no. 

Espero que se entienda la pregunta, y que se pueda responder!

**Comment by Hernan4444** [comment]
@fomorales si entendí bien tu pregunta, quieres saber cuando considerar algo transbordo o no??

Transbordo se considera como pasar por cualquier estacion que tenga más de dos estaciones como conexion, da lo mismo el camino que sigas. Si Pajaritos tiene 4 conexiones, entonces es una estacion de transbordo. Aquí no definiremos lineas como los típicos metros (nos gusta innovar).

Espero haber respondido tu duda
Saludos! ✌️

**Comment by fomorales** [comment]
Ok, gracias!

Pero por ejemplo, en el modelo 1 la estación Salvador y Baquedano son contiguas, pero ambas tienen más de dos conexiones. Entonces si hago ese viaje ¿haré dos transbordos? o ¿solo se consideran las estaciones que no son la primera ni la última?

Gracias!

**Comment by Hernan4444** [comment]
@fomorales considera como si hubieras hecho 2 transbordos. En el otro caso hubieramos especificado en el enuciado que solo consideren las estaciones que no son la primera ni la última.

Saludos!!

**Comment by fxalvarez** [comment]
En el Enunciado dice que son 2 **o más** estaciones, lo que qerría decir que la mayoria (si no todas) las estaciones serían transbordo?

Gracias.

**Comment by Hernan4444** [comment]
@fxalvarez en el enunciado dice:
> Transbordo: debe indicar la cantidad de transbordos existentes en esa ruta. Se define transbordo como
cualquier estación que permite tomar 2 o más líneas diferentes.

Con eso nos referimos a que durante el viaje en **esa ruta** tienes la opcion de tomar 2 o más lineas diferente, es decir, si mientras vas **avanzando**, tienes dos estaciones distintas a las que puedes ir, se considera transbordo. Notese que como estás  **avanzando**, considerar la estación en la que estabas antes como una estación diferente que ir no es lo lógico, puesto que te estás manteniendo en la misma linea que tu mismo dicidiste recorrer (no es una línea diferente).

Espero que haya quedado claro.
Saludos

**Comment by fxalvarez** [comment]
Perfecto, muchas gracias.
