### ISSUE TITLE
Simulación

### ISSUE THREAD

**Issue by saboetto** [IIC2115/Syllabus-2018-1#80]
Hola! para la actividad que vimos en clases de la simulación, el Profe al final dijo que modelar DES era muy complicado por el hecho de que todos los objetos se van moviendo, por lo que dijo que esa parte se podía hacer con el otro método de simulación continua. Aquí se puede hacer lo mismo? Porque tengo el mismo problema de como hacer mover a todas las entidades hasta encontrar el punto en que suceda algún evento. 
Gracias!

**Comment by Hernan4444** [comment]
@saboetto para la actividad permitimos hacerlo con simulación continua para evitar que perdieron mucho tiempo ahí, pero en esta tarea, que son 2 semanas, se espera que logren programar esta parte de forma discreta.

Saludos ✌️
