### ISSUE TITLE
Rango de muerte de lemmings en despegue

### ISSUE THREAD

**Issue by Tamarainfante** [IIC2115/Syllabus-2018-1#81]
Hola, 

Dado que el enunciado no especifica el rango donde un dron es capaz de matar lemmings al despegar ya sea a, b o c? O el dron que explota solo mata a los drones que atrapó?.

Espero su respuesta, 
Gracias :)

**Comment by Hernan4444** [comment]
@Tamarainfante el dron que explota solo mata a los drones que atrapó.

Saludos
