### ISSUE TITLE
Duda Actividad no evaluada martes 12/03

### ISSUE THREAD

**Issue by jmundurraga** [IIC2115/Syllabus-2018-1#85]
Cuando el héroe hace su grito de guerra el contrincante escapa? o solo no lo ataca durante ese turno?

**Comment by fnquinteros** [comment]
Hola! Realmente no importa. Si estas haciendo la actividad de nuevo para estudiar, puedes modelarlo como quieras, pretendemos evaluar interacción entre clases, no las funcionalidades específicas de la actividad :smile: Saludos!

**Comment by frosati1995** [comment]
holaa!  como puedo generar un numero con cierta probabilidad??
