### ISSUE TITLE
generar numero con cierta probabilidad

### ISSUE THREAD

**Issue by frosati1995** [IIC2115/Syllabus-2018-1#86]
Hola queria saber como se puede generar un numero con cierta probabilidad que yo determino

**Comment by Hernan4444** [comment]
@frosati1995 
 Esto dos links: [link_1](https://stackoverflow.com/questions/4265988/generate-random-numbers-with-a-given-numerical-distribution) y [link_2](https://stackoverflow.com/questions/43767141/generate-random-numbers-with-probability) fueron los primeros que me aparecieron tras buscar en google: "generate number with probability python", espero que responda tu duda.

Saludos
Hernán V.
