### ISSUE TITLE
atributos y objetos

### ISSUE THREAD

**Issue by ignaciacunich** [IIC2115/Syllabus-2018-1#87]
Hola,
¿Cómo se define la función __init__ de una clase si necesito darle como atributo un objeto de otra clase_?

Gracias!

**Comment by hanavarrete** [comment]
Hola! no es necesario hacer nada distinto a como se construye normalmente la función. Por ejemplo:
```python
def __init__(self, objeto):
      self.atributo = objeto
```
Eso es el caso en el que al momento de construir, el objeto ya esté inicializado (o en su defecto, se lo entregues inicializado en el constructor). Saludos!
