### ISSUE TITLE
Valores y Llaves en Diccionarios

### ISSUE THREAD

**Issue by aeavalos** [IIC2115/Syllabus-2018-1#88]
En los diccionarios, las llaves son las que se encuentran a la izquierda o a la derecha del ":"
En el material de clase sale: "varios = {1:'primera llave', '2': 'segunda llave', 23.0: 'tercera llave', (23,5): 'cuarta llave'}", pero en el ejemplo siguiente cuando se llama a los valores con sus llaves, se utiliza el elemento de la izquierda.

Desde ya muchas gracias.

**Comment by fnquinteros** [comment]
Hola, las llaves son los elementos de la izquierda. Los valores son los elementos de la derecha. Saludos!
