### ISSUE TITLE
[T01] Elección de ruta para contabilizar transbordos

### ISSUE THREAD

**Issue by Carlos0C** [IIC2115/Syllabus-2018-1#9]
Suponiendo que puedo, por ejemplo, disponer de la ruta más larga y la más corta entre dos estaciones.
¿Queda a mi criterio definir cual de estas dos rutas seguir para contabilizar la cantidad de transbordos en la consulta "Transbordo"?

Saludos

**Comment by Hernan4444** [comment]
@Carlos0C precisamente queda a tu criterio, pero no olvides agregar esa decisión en tu manual de usuario 📖 
Saludos!! ✌️

**Comment by Carlos0C** [comment]
Perfecto, muchas gracias !!!
