### ISSUE TITLE
[T01] Costo de inversión en atracciones

### ISSUE THREAD

**Issue by BrunoLertora** [IIC2115/Syllabus-2018-1#90]
El enunciado de la Tarea 1 dice que: "Cada vez que el dueño obtenga 500.000 HC, invertirá
la mitad de su capital en una nueva atracción, que será la que tenga el mayor costo de entrada", pero también se nos entrega un diccionario de atracciones con el costo de compra de cada una (costo_atracción). Entonces no entiendo cuánto dinero debe pagar el dueño para comprar una atracción, la mitad de su capital si logra tener sobre 500.000 HC o el costo de la atracción de mayor costo de entrada que aparece en la constante ATRACCIONES?

Gracias

**Comment by Hernan4444** [comment]
@BrunoLertora hola!!!, fue un error nuestro, precisamente gasta la mitad de su capital, ~voy a actualizar el archivo CONSTANTE (y enunciado) para que no aparezca el costo_atracción.~

Edit: No es necesario editarlo, ese dato sirve para determinar las atracciones más baratas.

Muchas gracias por avisar!!
Saludos ✌️

**Comment by aeavalos** [comment]
Pero gasta el valor de la atracción con costo mayor que le alcanza con la mitad de los HC y el resto vuelve al dinero del dueño? O pierde esa diferencia?

**Comment by Hernan4444** [comment]
@aeavalos Cuando el dueño compra una atracción, gasta si o si la mitad de los HC (sin importar el `costo_atracción` que tenga la atracción). Al final el `costo_atracción` es solo para que su simulación pueda escoger las 4 atracciones más baratas de la lista de atracciones cuando empieza la simulación, luego ya no es de utilidad.

Espero haber respondido tu duda.
Saludos ✌️

**Comment by cristianhojas** [comment]
Y se puede dar el caso de que en algún minuto dado, el dueño tenga mas de 500.000 HC?? 
Por ejemplo, supongamos que al final de un tiempo t1, el dueño queda con 600.000 HC.
En este caso invierte 300.000 en la atracción mas cara, sin importar el precio que tenga esta ??

**Comment by Hernan4444** [comment]
@cristianhojas así es, cuando termine el tiempo t1, si la cantidad es mayor a 500.000, se toma la mitad, en tu caso se invierte 300.000.

Saludos

**Comment by fjmunoz3** [comment]
Deduzco entonces que al principio se elijen las 4 más caras y cuando el dueño alcanza los 500.000 HC elije la más barata (siempre la misma). ¿Es así? ¿O elijirá la más barata que aún no esté en el parque?
Asociado a esto,¿ puede haber más de una atracción de un mismo tipo?

**Comment by Hernan4444** [comment]
@fjmunoz3 no puede haber más de una atracción iguales, cumpla 1 y ya no se puede comprar otra. Además, en el enunciado se dice que compra la atracción de mayor costo de entrada, no la más barata.

Saludos ✌️

**Comment by vjcontreras** [comment]
Entonces, si alcanzo los 500.000, agrego la atracción de costo de entrada más cara de las que quedan y me quedo con la mitad del dinero (250.000), ¿sin importar el costo de construcción de la atracción?

**Comment by Hernan4444** [comment]
@vjcontreras así es.
Saludos ✌️
