### ISSUE TITLE
[T01] Constante PERSONAS no es Lista de Tuplas

### ISSUE THREAD

**Issue by BrunoLertora** [IIC2115/Syllabus-2018-1#93]
Hola, el enunciado dice que la constante PERSONAS: "posee una lista de tuplas en donde cada tupla representa a una persona enla simulación", pero en el archivo CONSTANTES.py, PERSONAS es sólo una lista con todos los datos de cada persona.

PERSONAS = [
	 27572, 45, 'Amber Gutierrez', '2005-10-16',
	 65694, 228, 'Michael Dunn', '2005-03-11',
         ....
	 34504, 92, 'Carla Brown', '2007-06-22'
]

**Comment by Hernan4444** [comment]
@BrunoLertora ya actualicé el archivo, fue un error mío.

Saludos ✌️

**Comment by BrunoLertora** [comment]
@Hernan4444 Gracias!

**Comment by duncanclassic** [comment]
Profesor, la lista PERSONAS viene con un pequeño error que me dio un dolor de cabeza por un buen rato:

(34504, 92, 'Carla Brown', '2007-06-22)'
]

la lista de tuplas termina asi , por lo que tira error al importarlo, hay que cambiar la comilla por el parentesis, por si a alguien le sirve.
