### ISSUE TITLE
[T01] Input PERSONAS

### ISSUE THREAD

**Issue by josetov** [IIC2115/Syllabus-2018-1#94]
En el enunciado dicen que la lista PERSONAS posee una tupla por cada persona, pero en Constantes.py solo existe una lista con 400 datos (sin separar en tuplas). Entonces ¿hay un error en el enunciado o debemos parsear la lista cada 4 datos recorridos?
Pregunto para que mi código pueda correr con el imput que utilicen para corregir

Gracias

**Comment by Hernan4444** [comment]
Hola, #93 

Saludos ✌️
