### ISSUE TITLE
[T01] FALLA ATRACCION

### ISSUE THREAD

**Issue by jorgevaldesmery** [IIC2115/Syllabus-2018-1#95]
Cuando una atracción falla ¿Qué pasa con las personas que están en la fila de esa atracción?

**Comment by Hernan4444** [comment]
@jorgevaldesmery todas esas personas se van en el mismo orden a la cola de la siguiente atracción que pueden pagar.

**Comment by svigneaux** [comment]
Cuando los visitantes se van a la nueva atracción, también deben pagarla?

**Comment by Hernan4444** [comment]
@svigneaux sip, pero uno paga cuando se sube, no cuando hace cola a algo.

Saludos ✌️
