### ISSUE TITLE
[T01] sobre iportacion de datos

### ISSUE THREAD

**Issue by conagu** [IIC2115/Syllabus-2018-1#97]
Hola! Tengo algunas preguntas:
1. Para leer los datos de las personas y de las atracciones, solo las copio en el código o se deben leer como un archivo de texto?
2. cuál es la unidad de tiempo del while, horas o días ?

Gracias :)

**Comment by hanavarrete** [comment]
Hola! Debes leer el archivo, no pegarlo. Sobre lo segundo, son minutos. Saludos!

**Comment by frosati1995** [comment]
Hola, por lo que hable con el profesor el archivo hay que importarlo no leerlo y no se con que comandos se importa e archivo.
Saludos!

**Comment by Hernan4444** [comment]
@frosati1995 esa información se puede encontrar googleando un poco, la idea de la tarea es que también investiguen algunas cosas.

Saludos ✌️
