### ISSUE TITLE
Tarea-Duplicar precio entrada

### ISSUE THREAD

**Issue by fjorrego** [IIC2115/Syllabus-2018-1#98]
En el enunciado sale "Cuando el dueño disponga de menos de 100.000 HC, duplicará los precios de todas las atracciones con las que cuenta en ese momento" Esto significa que cuando vuelva a tener más de 100.000 HC, los precios de entrada volverán a los normales?

**Comment by Hernan4444** [comment]
@fjorrego no, no se vuelven a los precios normales.
Saludos ✌️

**Comment by nmayne14** [comment]
cuando se duplican los precios, son solo los del parque o se duplican los precios de las posibles atracciones a agregar tambien?

**Comment by Hernan4444** [comment]
@nmayne14 son solo del parque.
Saludos ✌️
