### ISSUE TITLE
Tarea 01: Indemnizacion

### ISSUE THREAD

**Issue by jcbarriga** [IIC2115/Syllabus-2018-1#99]
En el enunciado sale que el costo por menores de edad, es decir 18 años, evacuados es de 20000 HC, y el resto de 10000 HC. Dado que en la lista PERSONAS no se encuentra nadie con más de 18 años, no será que el costo aumentado debiese ser para personas menores de 8 años ?

**Comment by Hernan4444** [comment]
@jcbarriga nosotros podemos (y vamos) a corregir la tarea con datos de otras personas y ahí si tendremos mayores de edad, así que se mantiene como está el enunciado.

Saludos ✌️
